<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle();?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl.'css/'.$this->template.'.css'); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl.'css/jquery-ui-1.8.16.custom.css'); ?>
	
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'js/fancybox/jquery.fancybox-1.3.1.css'); ?>
	<?php $this->headScript()->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-pl.js') 
									->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-cs.js') 
									->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-sk.js')
									->appendFile($this->baseUrl.'js/simple/ajax.js')
									->appendFile($this->baseUrl.'js/simple/script.js'); ?>
									
	<?php if ($this->user->role == 'admin')
		$this->headScript()->appendFile($this->baseUrl.'js/simple/admin_script.js');?>
	
	<?php echo $this->headScript();?>
</head>

<body>
	<header id="header" name="<?php echo $this->lang;?>">
		<?php if ($this->flash):?>
		<div id="flash">
			<p class="flash <?php echo $this->flash_bg;?>"><?php echo $this->translation($this->flash);?></p>
      	</div>
      	<?php endif;?>
	  	<div class="header">
		    <div class="logo">
			    <a href="<?php echo $this->url(array('lang' => $this->lang), 'main');?>">
			    	<object width="130" height="130" data="<?php echo $this->baseUrl;?>img/simple/logo.swf"></object>
			    	<img src="<?php echo $this->baseUrl('img/simple/graduation-projects-eu_logo_'.$this->lang.'.png');?>"
			    		alt="Gradutation Project Logo"/>
			    </a>
			</div>
	  	</div>

		<div class="top-menu">
		    <?php echo $this->partial('partials/current_edition.phtml', array('lang' => $this->lang, 'edition' => $this->edition));?>
		    <?php echo $this->partial('partials/previous_edition.phtml', array('edition_list' => $this->edition_list, 'edition' => $this->edition, 'lang' => $this->lang));?>
		    
		    <?php if ($this->user->role == 'admin'):?>
		    <?php echo $this->partial('partials/admin_panel.phtml', array('edition_list' => $this->edition_list, 'edition' => $this->edition, 'lang' => $this->lang));?>
		    <?php endif;?>
		    
		    <?php echo $this->partial('partials/lang_menu.phtml', array('link' => $this->link, 'lang' => $this->lang));?>
		    
		</div>
		
		<p class="hr"><span>&nbsp;</span></p>
		
	</header>
	
	<?php if (isset($this->path)):?>
	<nav class="path">
	<?php foreach($this->path as $i => $elem):?>
		<a href="<?php echo $this->url($elem['data'], $elem['route']);?>" <?php if (++$i == count($this->path)):?>class="path_end"<?php endif;?>>
			<?php foreach($elem['name'] as $string) {echo $this->translate($string).' ';}?>
		</a> <?php if ($i != count($this->path)):?>&raquo;<?php endif;?>
	<?php endforeach;?>
	</nav>
	<?php endif;?>
	

	<?php echo $this->layout()->content; ?>

	

	<footer>
		<p> Copyright by 2+3D, 2011. Projekt wydany dzięki pomocy finansowej  
	    Międzynarodowego Funduszu Wyszehradzkiego 
	    www.visegradfund.org</p>
	    <p><img src="<?php echo $this->baseUrl('img/simple/visegrad_fund_logo_web_blue_400.jpg');?>" alt="Visegrad Fund"></p>
	</footer>


</body>
</html>