<?php echo $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html;charset=utf-8" />
	<meta name="Keywords" content="graduation projects, praace dyplomowe, design" />
	<meta name="Description" content="Skrypt pozwalający w łatwy sposób zarządzać własnym księgozbiorem" />
	<meta name="author" content="Artur Jewuła" />
	<!-- link href="http://webfonts.fontslive.com/css/ebf21b27-0dc5-4085-9c64-175f9395fa6a.css" rel="stylesheet" type="text/css" / -->
	<?php echo $this->headTitle();?>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'css/'.$this->template.'.css'); ?>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'css/jquery-ui-1.8.9.custom.css'); ?>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'js/fancybox/jquery.fancybox-1.3.1.css'); ?>
	<?php echo $this->headScript()->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-pl.js') 
									->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-cs.js') 
									->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-sk.js') 
									->appendFile($this->baseUrl.'js/simple/script.js'); ?>
	
</head>
<body>
	<div id="flash">
		<p class="flash <?php echo $this->flash_bg;?>"><?php echo $this->translation($this->flash);?></p>
	</div>
	
	<div class="main">
		<a href="<?php echo $this->baseUrl;?>">
			<img src="<?php echo $this->baseUrl;?>img/simple/logo_<?php echo strtoupper($this->lang);?>.png" id="header" name="<?php echo $this->lang;?>" alt="logo" />
		</a>
		<p class="spacer_small">&nbsp;</p>

		<div id="content">
			<?php echo $this->layout()->content; ?>
			<p class="spacer_small">&nbsp;</p>
		</div>
		
		<p id="content_spacer">&nbsp;</p>
				
		<p class="partners">
			<?php echo $this->translate('Partners', 'cz');?> 
			| <?php echo $this->translate('Partners');?> | 
			<?php echo $this->translate('Partners', 'sk');?>
		</p>
		
		<div id="footer">
			<p class="footer_paragraph" style="margin-left: 35px;">
				<a href="http://www.typo.cz/" target="_blank">
					<img src="<?php echo $this->baseUrl;?>img/simple/logo_typo.png" alt="Typo" />
				</a>
			</p>
			<p class="footer_paragraph">
				<a href="http://www.2plus3d.pl/" target="_blank">
					<img src="<?php echo $this->baseUrl;?>img/simple/logo_2plus3d.png" alt="2+3D Magazine" />
				</a>
				<a href="http://www.zamekcieszyn.pl/" target="_blank">
					<img src="<?php echo $this->baseUrl;?>img/simple/logo_zamek.png"  style="margin-right: 0px;" alt="{$lang.silesia_castle}" />
				</a>
			</p>
			<p class="footer_paragraph">
				<a href="http://www.sdc.sk/index.php?lang=en&amp;menu=designum" target="_blank">
					<img src="<?php echo $this->baseUrl;?>img/simple/logo_designum.png" alt="designum" />
				</a>
			</p>
			<p class="spacer">&nbsp;</p>
			
			<p class="footer_paragraph" style="margin-left: 35px;">
				<?php echo $this->translations['cs']['footer_visegrad'];?>
			</p>
			<p class="footer_paragraph">
				<?php echo $this->translations['pl']['footer_visegrad'];?>
			</p>
			<p class="footer_paragraph">
				<?php echo $this->translations['sk']['footer_visegrad'];?>
			</p>
			<p class="spacer">&nbsp;</p>
				<a href="http://www.visegradfund.eu/" target="_blank">
					<img src="<?php echo $this->baseUrl;?>img/simple/logo_visegrad.png" class="visegradfund" alt="Visegrad Fund" />
				</a>
			<p class="spacer_small">&nbsp;</p>
			
		</div>
		<p class="subfooter">&copy; 2010 Fundacja Rzecz Piękna WFP ASP Kraków. Wszelkie prawa zastrzeżone.
			<br />
			Wykonanie strony: Zefiryn	
		</p>
	</div>

</body>
</html>