<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle();?>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'css/'.$this->template.'.css'); ?>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'css/jquery-ui-1.8.9.custom.css'); ?>
	
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'js/fancybox/jquery.fancybox-1.3.1.css'); ?>
	<?php echo $this->headScript()->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-pl.js') 
									->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-cs.js') 
									->appendFile($this->baseUrl.'js/i18n/jquery.ui.datepicker-sk.js')
									->appendFile($this->baseUrl.'js/simple/ajax.js')
									->appendFile($this->baseUrl.'js/simple/script.js'); ?>
</head>

<body>
	<header>
		<div id="flash">
			<p class="flash <?php echo $this->flash_bg;?>"><?php echo $this->translation($this->flash);?></p>
      	</div>
	  	<div class="header">
		    <div class="logo">
			    <a href="<?php echo $this->url(array('lang' => $this->lang), 'main');?>">
			    	<img src="/img/simple/graduation-projects-eu_logo.png"/>
			    </a>
			</div>
	  	</div>
	  
		<div class="top-menu">
		    <?php echo $this->partial('partials/current_edition.phtml', array('lang' => $this->lang));?>
		    <?php echo $this->partial('partials/previous_edition.phtml', array('edition_list' => $this->edition_list, 'edition' => $this->edition, 'lang' => $this->lang));?>
		    
		    <?php if ($this->user->role == 'admin'):?>
		    <?php echo $this->partial('partials/admin_panel.phtml', array('edition_list' => $this->edition_list, 'edition' => $this->edition, 'lang' => $this->lang));?>
		    <?php endif;?>
		    
		    <?php echo $this->partial('partials/lang_menu.phtml', array('link' => $this->link, 'lang' => $this->lang));?>
		</div>
	</header>


	<?php echo $this->layout()->content; ?>


	<div id="footer">
		<p> Copyright by 2+3D, 2011. Projekt wydany dzięki pomocy finansowej  
	    Międzynarodowego Funduszu Wyszehradzkiego 
	    www.visegradfund.org</p>
	    <p><img src="/img/simple/visegrad_fund_logo_web_blue_400.jpg" alt="Visegrad Fund"></p>
	</div>


</body>
</html>