<p class="admin">
	<a href="<?php echo $this->baseUrl('/faq/edit');?>">
		<img src="/img/simple/empty.png" class="ui-icon ui-icon-pencil no-block" 
			alt="<?php echo $this->translate('edit');?>" 
			title="<?php echo $this->translate('edit');?>">
	</a>
	<a href="<?php echo $this->baseUrl('/faq/delete');?>"
		class="delete">
		<img src="/img/simple/empty.png" class="ui-icon ui-icon-trash no-block" 
			alt="<?php echo $this->translate('delete');?>" 
			title="<?php echo $this->translate('delete');?>">
	</a>
</p>