<div id="main">
	<?php if ($this->user->_role == 'admin') 
			echo $this->partial('faq/_admin.phtml');?>
	<h1><?php echo $this->translate('faq_header');?></h1>
	<p class="spacer">&nbsp;</p>
	
	<?php foreach($this->faqs as $index => $faq):?>
	<p class="rule">
		<span style="font-weight: bold">
				<?php echo ++$index.'. '.$faq->faq_question;?>
		</span><br />
		<?php echo  $faq->faq_answer;?>
	</p> 
	<?php endforeach; ?>
</div>