<?php echo $this->partial('partials/lang_menu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'link' => 'faq',
						'lang' => $this->lang));
?>
<div class="content">
	<h1><?php echo $this->translate('faq_header');?></h1>
	<p class="spacer">&nbsp;</p>
	
	<?php foreach($this->faqs as $index => $faq):?>
	<p class="rule">
		<span style="font-weight: bold">
				<?php echo ++$index.'. '.$faq->_faq_question;?>
		</span><br />
		<?php echo  $faq->_faq_answer;?>
	</p> 
	<?php endforeach; ?>
</div>

<?php echo $this->partial('partials/submenu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'faq' => TRUE));
?>

<p class="spacer_small">&nbsp;</p> 
<p class="previous"><a href="<?php echo $this->baseUrl;?>">&lt; <?php echo $this->translate('previous_page');?></a></p>
