<?php $winners = array();?>
<?php $qualified = array();?>
<?php if (count($this->applications) > 0):?>
<div class="applications final-stage">
<?php foreach ($this->applications as $worktype => $countries):?>
  <div class="worktype">
  <h2><?php echo $worktype?></h2>
  <?php foreach($countries as $code => $apps):?>
    <div class="country country-<?php echo $code;?> type-<?php echo $worktype;?>">
    <h3><?php echo $code; ?>: <span class="work-count">0</span></h3>
    <?php foreach($apps as $id => $application):?>
      <?php if (!$application->countScore($this->currentStage->stage_id)):?>
      <?php @$qualified[$worktype][$code] += 1;?>
      <div class="app-wrapper" data-country="<?php echo $code;?>" data-type="<?php echo $worktype;?>" data-app-id="<?php echo $application->application_id;?>">
        <a href="<?php echo $this->url(array('id' => $application->application_id, 'lang' => $this->lang), 'lang_application');?>">
          <img src="<?php echo $this->baseUrl('/assets/applications/'.$application->getMiniature()); ?>" 
              class="miniature" title="<?php echo $application->work_subject;?>"/>        
        </a>
      </div>
      <?php endif;?>
    <?php endforeach; ?>
    </div>    
  <?php endforeach; ?>
  </div>
<?php endforeach; ?>
</div>
<?php endif;?>

<div class="applications winning-apps">
  <?php foreach ($this->applications as $worktype => $countries):?>
  <div class="worktype">
    <h2><?php echo $worktype?></h2>
    <?php foreach($countries as $code => $apps):?>
    <div class="country country-<?php echo $code;?> type-<?php echo $worktype;?>">
      <h3><?php echo $code; ?>: <span class="work-count">0</span></h3>
      <?php foreach($apps as $id => $application):?>
        <?php if ($application->countScore($this->currentStage->stage_id) > 0):?>
        <?php @$winners[$worktype][$code] += 1;?>
        <div class="app-wrapper" data-country="<?php echo $code;?>" data-type="<?php echo $worktype;?>" data-app-id="<?php echo $application->application_id;?>">
          <a href="<?php echo $this->url(array('id' => $application->application_id, 'lang' => $this->lang), 'lang_application');?>">
            <img src="<?php echo $this->baseUrl('/assets/applications/'.$application->getMiniature()); ?>" 
                class="miniature" title="<?php echo $application->work_subject;?>"/>
          </a>
        </div>
        <?php endif;?>
      <?php endforeach; ?>
    </div>
    <?php endforeach; ?>
  </div>
  <?php endforeach; ?>
</div>

<script type="text/javascript">
  var winners = <?php echo json_encode($winners);?>;
  var qualified = <?php echo json_encode($qualified);?>
</script>

<p class="clearfix">&nbsp;</p>
