<?php 
$admin = $this->user->_role == 'admin' ? TRUE : FALSE;
$juror = $this->user->_role == 'juror' ? $this->user->juror : FALSE;
?>
<table class="applications">
	<!--TABLE HEADERS-->
  <thead>
    <tr class="header">
      <!--ID-->	
      <th class="normal" style="width: 20px;">
        #
      </th>
      <!--UID-->
      <th class="left" style="width: 15px;">
        UID
      </th>
      <!--MINIATURE-->
      <th class="left" style="width: 80px;">
        <?php echo $this->translate('miniature');?>
      </th>
      <!--NAME-->
      <th class="normal" style="width: 70px;">
        <?php echo $this->translate('user_name_and_surname');?>
      </th>
      
      <!--COUNTRY-->
      <th class="normal" style="width: 20px;">
        <?php echo $this->translate('country');?>
      </th>
      
      <!--2d/3d-->
      <th class="normal" style="width: 35px;">
        <?php echo $this->translate('work_type');?>
      </th>
      
      <!--SUBJECT-->
      <th class="normal" style="width: 140px;">
        <?php echo $this->translate('work_subject');?>
      </th>
      
      <!-- DEGREE -->
      <th class="normal" style="width: 30px;">
        <?php echo $this->translate('degree');?>
      </th>		
      
      <!--FILES LIST-->
      <th class="normal" style="width: 130px;">
        <?php echo $this->translate('application_files');?>
      </th>
      <!--VOTE LINK-->
      <th class="normal" style="width: 235px;">
        <?php echo $this->translate('vote');?>
      </th>
      
      <!--CHECKBOX FOR MANAGING-->
      <th class="left" style="width: 15px;">
        
      </th>
    </tr>
  </thead>
	<!--END OF TABLE HEADERS-->

  <tbody>
    <?php if (count($this->applications) > 0):?>
    <!--APPLICATIONS DATA -->
    <?php $no = 0; 
    foreach ($this->applications as $application):?>
    <tr class="applicationData <?php if ($no%2 == 0):?>grey<?php endif;?>" 
      data-application-id="<?php echo $application->application_id?>"
      <?php if($juror) echo 'data-juror-grade="'.$application->getJurorVote($this->currentStage->stage_id, $juror->juror_id).'"'; ?>
      data-application-score="<?php echo $application->countScore($this->currentStage->stage_id)?>">
      
      <!-- # -->
      <td class="normal lp" style="width: 20px;"><?php echo ++$no;?></td>
      
      <!-- UID -->
      <td class="normal" style="width: 15px;"><?php echo $application->application_id;?></td>
      
      <!-- MINIATURE -->
      <td class="left" style="width: 80px;">
        <?php if ($application->hasFiles()):?>
        <img src="<?php echo $this->baseUrl('/assets/applications/'.$application->getMiniature()); ?>" 
          class="miniature" rel="application_<?php echo $application->application_id;?>"/>
        <?php endif;?>
      </td>
      <!-- USER -->
      <td class="normal username" style="width: 70px;">
        <a href="<?php echo $this->url(array('id' => $application->application_id, 'lang' => $this->lang), 'lang_application');?>">
          <?php echo $application->user->name?><br />
          <span class="bold"><?php echo $application->user->surname ?></span>
        </a>
      </td>
      
      <!-- COUNTRY -->
      <td class="normal" style="width: 20px;"><?php echo $this->translate($application->country);?></td>
      
      <!-- WORK TYPE -->
      <td class="normal" style="width: 35px;"><?php echo $application->work_type->work_type_name;?></td>
      
      <!-- SUBJECT -->
      <td class="normal work_subject" style="width: 140px;">
        
        <?php if (count($application->disputes) > 0):?>
        <?php echo $this->partial('applications/_dispute.phtml', array('application' => $application)); ?>
        <?php endif;?>
        
        <?php echo $application->work_subject;?>
      </td>
      
      <!-- DEGREE -->
      <td class="normal" style="width: 30px;"><?php echo $this->translate($application->degree->degree_name);?></td>
      
      
      <!-- FILES -->
      <td class="normal" style="width: 130px;">
        <?php foreach($application->files as $id => $file):?>
        <a href="<?php echo $this->baseUrl('/assets/applications/'.$file->path);?>"
          class="application_files index_application_files"
          rel="application_<?php echo $application->application_id;?>">
          <?php echo ++$id;?> 
        </a>
        <?php endforeach;?>
      
      </td>
      
      <!-- VOTES -->
      <td class="normal" style="width: 235px;">
    
      <?php if ($juror && $this->currentStage->active)  :?>
        <?php           
          $vote = $application->getJurorVote($this->currentStage->stage_id, $juror->juror_id);
          $vote = $vote != null ? (int)$vote : $vote;
        ?>
        <p class="votes">
        <?php for($i = 0; $i <= $this->currentStage->stage_max_vote; $i++):?>
          <?php //set class
              $class = '';
              if (($i*$juror->wage) === $vote) 
              {
                if ($i == 0) $class = 'voted vote_first';
                elseif ($i == $this->currentStage->stage_max_vote) $class = 'voted vote_last';
                else $class = 'voted vote_'.$i;
              }
          ?>
          <span class="vote <?php echo $class;?>"
            data-juror-id="<?php echo $juror->juror_id?>" data-stage-id="<?php echo $this->currentStage->stage_id?>" 
            data-vote="<?php echo $i?>" data-application-id="<?php echo $application->application_id?>">
            <?php if ($this->currentStage->translate)
              {
                echo $this->translate('stage_'.$this->currentStage->order.'_vote_'.$i);
              }
              else 
              {
                echo $i*$juror->wage;
              }
            ?>
          </span>
        
        <?php endfor;?>
        </p>
        <p class="clear"></p>
        <?php elseif ($juror && $this->currentStage->active == 0):?>
        <p><?php echo $this->translate('stage_closed');?></p>
          
        <?php elseif ($admin):?>
          <!-- GET EACH JURORS VOTE -->
          <div class="application_votes">
          <?php foreach($this->votes[$application->application_id] as $juror_id =>  $juror_vote):?>
            <!-- CREATE FIELDS FOR VOTES FOR EACH JUROR-->
              <p class="votes">
                <span class="juror_name"><?php echo $juror_vote['juror_name']?>:</span>
                <?php for($i = 0; $i <= $this->currentStage->stage_max_vote; $i++):?>
                <?php //set class
                    $class = '';
                    if (($i*$juror_vote['wage']) === $juror_vote['vote']) 
                    {
                      if ($i == 0) $class = 'voted vote_first';
                      elseif ($i == $this->currentStage->stage_max_vote) $class = 'voted vote_last';
                      else $class = 'voted vote_'.$i;
                    }
                ?>                
                  <span class="admin_vote <?php echo $class;?>" data-juror-id="<?php echo $juror_id?>" 
                      data-stage-id="<?php echo $this->currentStage->stage_id?>" 
                      data-vote="<?php echo $i?>" data-application-id="<?php echo $application->application_id?>"
                      
                  ><?php echo  $i*$juror_vote['wage']; ?></span>
                <?php endfor;?>
              </p>
              <p class="clear" style="height: 2px;"></p>	
          <?php endforeach;?>
              <p class="votes qualification-status">
                <span class="juror_name"><?php echo $this->translate('qualification_status');?>:</span>
                <?php $qualification_status = $application->inStage($this->currentStage->getNextStage());?>
                <span class="qualification_status_info" id="status-qualified" style="<?php if ($qualification_status == false):?>display: none;<?php endif;?>"><?php echo $this->translate('qualified');?></span>
                <span class="qualification_status_info" id="status-notqualified" style="<?php if ($qualification_status == true):?>display: none;<?php endif;?>"><?php echo $this->translate('notqualified');?></span>
              </p>
              <p class="clear" style="height: 2px;"></p>  
          </div>
        <?php endif;?>
      </td>
      
      <!-- ADMIN ACTION -->
      <td class="admin_column" style="width: 15px;vertical-align: top;">
        
        <?php if ($admin):?>
        <input type="checkbox" id="app<?php echo $application->application_id?>" name="app[<?php echo $application->application_id?>]" class="admin_button" />
        
        <img src="<?php echo $this->baseUrl('/img/simple/empty.png');?>" class="ui-icon ui-icon-check click no-block"
          id="check_app<?php echo $application->application_id?>" 
          alt="<?php echo $this->translate('check');?>" 
          title="<?php echo $this->translate('check');?>"/>
        
        <a
          href="<?php echo $this->url(array('id' => $application->application_id), 'edit_application');?>">
          <img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
          class="ui-icon ui-icon-mail-closed no-block"
          alt="<?php echo $this->translate('send_mail');?>"
          title="<?php echo $this->translate('send_mail');?>" />
        </a>
        <a class="dispute" data-application-id="<?php echo $application->application_id?>" 
          data-marked="<?php echo (int)$application->isDisputed($this->user);?>">
          <img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
            class="ui-icon ui-icon-comment no-block"
            alt="<?php echo $this->translate('mark_to_dispute');?>"
            title="<?php echo $this->translate('mark_to_dispute');?>" />
          </a>
        
        <a
          href="<?php echo $this->url(array('id' => $application->application_id), 'edit_application');?>">
          <img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
          class="ui-icon ui-icon-pencil no-block"
          alt="<?php echo $this->translate('edit');?>"
          title="<?php echo $this->translate('edit');?>" />
        </a>
        <a
          href="<?php echo $this->url(array('id' => $application->application_id), 'delete_application');?>"
          class="delete"> <img
          src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
          class="ui-icon ui-icon-trash no-block" del="Usuń"
          alt="<?php echo $this->translate('delete');?>"
          title="<?php echo $this->translate('delete');?>" />
        </a>
          
        
        <?php else: ?>
        
        <!-- DISPUTE BUTTONS FOR JURORS -->
        <div class="dispute" data-application-id="<?php echo $application->application_id?>" data-marked="<?php echo (int)$application->isDisputed($this->user);?>">
        
        <?php if ($application->isDisputed($this->user)):?>
          <span class="dispute">&ndash;</span>
          <span class="hint"><?php echo $this->translate('marked_to_dispute');?></span>
        <?php else: ?>
          <span class="dispute">&plus;</span>
          <span class="hint"><?php echo $this->translate('mark_to_dispute');?></span>
        <?php endif;?>
        </div>
        
        <?php endif;?>
        
      </td>	
    </tr>
    <?php endforeach;?>
    
    <?php else: ?>
    <!-- NO APPLICATIONS -->
    <tr>
      <td colspan="11" style="font-size: 24px;text-align: center;padding: 20px 0px;">
        <?php echo $this->translate('no_applications_for_current_selection');?>
      </td>
    </tr>		
    
    <?php endif;?>
  </tbody>
</table>

<table class="stats"> 
  <tr class="header"> 
    <th colspan="5"><?php echo $this->translate('statistics');?></th> 
  </tr> 
  <tr>
    <th></th> 
    <?php foreach ($this->statistics['pl'] as $type => $ammount):?>
    <th class="normal"><?php echo $this->translate($type);?></th>
    <?php endforeach;?> 
  </tr> 
  <?php foreach($this->statistics as $part => $stats):?>
  <tr>
    <td class="left"><?php echo $this->translate('stat_'.$part);?></td>
    <?php foreach ($stats as $type => $ammount):?>
    <td><?php echo $ammount;?></td>
    <?php endforeach;?>
  </tr>
  <?php endforeach;?>
</table>