<div id="main">
	<h1>
	<?php echo $this->translate('confirm_application_header'); ?></h1>
	
	
	
	<?php 
		$data = $this->form->getValues();
		$appSettings = Zend_Registry::get('appSettings');
	?>
	<p><?php echo $this->translate('confirmation_explain');?></p>
	
	<div class="column-left">
		<p>
			<span class="label"><?php echo $this->translate('nick')?></span>: <?php echo $data['user']['nick'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('name')?></span>: <?php echo $data['user']['name'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('surname')?></span>: <?php echo $data['user']['surname'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('address')?></span>: <?php echo $data['user']['address'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('phone')?></span>: <?php echo $data['user']['phone'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('email')?></span>: <?php echo $data['user']['email'];?>
		
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('country')?></span>: <?php echo $this->form->getElement('country')->getMultiOption($data['country']);?>
		</p>
			
		<p>
			<span class="label"><?php echo $this->translate('school')?></span>: <?php echo $data['school'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('department')?></span>: <?php echo $data['department'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('degree')?></span>: <?php echo $this->form->getElement('degree_id')->getMultiOption($data['degree_id']);?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('work_subject')?></span>: <?php echo $data['work_subject'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('work_type')?></span>: <?php echo $this->form->getElement('work_type_id')->getMultiOption($data['work_type_id']);?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('work_desc')?></span>: <?php echo $data['work_desc'];?>
		</p>
		
		<p>
			<span class="label"><?php echo $this->translate('supervisor')?></span>: <?php echo $data['supervisor_degree'].' '.$data['supervisor'];?>
		</p>
			
		<p>
			<span class="label"><?php echo $this->translate('graduation_time')?></span>: <?php echo $data['graduation_time'];?>
		</p>
	</div>
	
	<div class="column-right">
		<p class="label"><?php echo $this->translate('application_files');?></p>
		<div id="app_images">
		<?php for ($i = 1; $i <= $appSettings->max_files; $i++): ?>
			<?php 
				$file = $this->form->getSubForm('file_'.$i);
				$cache = 'file_'.$i.'Cache';
				$id = 'file'.$i.'_id';

				//get the data for delete link
				if ($file->$id != null)
					$file_id = $file->$id;
				else
					$file_id = substr($file->$cache->getValue(), strrpos($file->$cache->getValue(), '/')+1);
				
				if ($file->$cache->getValue() != null):?>
			<div>
			<a 	class="form_file"
				href="<?php echo $this->baseUrl('/assets/'.$file->$cache->getValue());?>"
				rel="cache" >
				<img src="<?php echo $this->baseUrl('/assets/'.$file->$cache->getValue());?>" alt="" />
			</a>
			<?php if ($i % 4 == 0):?><p class="clearfix"></p><?php endif;?>
			</div>
			<?php endif;?>
		<?php endfor;?>
		<p class="clearfix"></p>
		</div>
	</div>
	<p class="clearfix"></p>
	
	<form method="post" action="<?php echo $this->url(array(),'application_save');?>" style="margin-top: 30px;">
			<p class="submit center">
				<input type="submit" name="correct" id="correct" value="<?php echo $this->translate('correct');?>" class="submit unprefered">			
				<input type="submit" name="confirm" id="confirm" value="<?php echo $this->translate('confirm')?>" class="submit prefered">
			</p>
	</form>
	
</div>
