<?php echo $this->partial('partials/lang_menu.phtml', 
			array('link' => 'applications', 'lang' => $this->lang));
?>

<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'editions', 'delete_confirm' => $this->translate('application_delete_confirm')));
?>

<div class="content">
	<h1><?php echo $this->translate('applications_header'); ?></h1>
	
	<?php if (count($this->applications) > 0):?>
	<p class="clear">&nbsp;</p>
	
	<table class="applications">
		<!--TABLE HEADERS-->
		<tr class="header">
			<!--CHECKBOX FOR MANAGING-->
			<th class="left" style="width: 15px;">
				&nbsp;
			</th>
			<!-- MINIATURE -->
			<th class="normal" style="width: 90px;">
				<?php echo $this->translate('miniature');?>
			</th>
			<!--ID-->	
			<th class="normal" style="width: 20px;">
				#
			</th>
			<!--NAME-->
			<th class="normal" style="width: 100px;">
				<a href="<?php echo $this->url(array('sort' => 'surname'), 'applications_sort');?>">
				<?php echo $this->translate('user_name_and_surname');?>
				</a>
			</th>
			<!--COUNTRY-->
			<th class="normal" style="width: 20px;">
				<a href="<?php echo $this->url(array('sort' => 'country'), 'applications_sort');?>">
				<?php echo $this->translate('country');?>
				</a>
			</th>
			<!--SUBJECT-->
			<th class="normal" style="width: 85px;">
				<a href="<?php echo $this->url(array('sort' => 'work_subject'), 'applications_sort');?>">
				<?php echo $this->translate('work_subject');?>
				</a>
			</th>
			<!--2d/3d-->
			<th class="normal" style="width: 35px;">
				<a href="<?php echo $this->url(array('sort' => 'work_type_name'), 'applications_sort');?>">
				<?php echo $this->translate('work_type');?>
				</a>
			</th>
			<!--FILES LIST-->
			<th class="normal" style="width: 50px;">
				<?php echo $this->translate('application_files');?>
			</th>
			<!--VOTE LINK-->
			<th class="normal" style="width: 90px;">
				<?php echo $this->translate('vote');?>
			</th>
			<!--ANNOTATIONS-->
			<th class="right" style="width: 40px;">
				<?php echo $this->translate('annotations');?>
			</th>
		</tr>
		<!--END OF TABLE HEADERS-->
		
		<!--APPLICATIONS DATA -->
		<?php foreach ($this->applications as $no => $application):?>
		<tr <?php if ($no%2 == 0):?>class="grey"<?php endif;?>>
			<td class="left" style="width: 15px;vertical-align: top;">
				<?php if ($this->user->_role == 'admin'):?>
				<input type="checkbox" id="app<?php echo $application->application_id?>" name="app[<?php echo $application->application_id?>]" class="admin_button" />
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-check no-block" 
					alt="<?php echo $this->translate('check');?>" 
					title="<?php echo $this->translate('check');?>"/>
				<?php echo $this->partial('applications/_admin.phtml', array('application' => $application, 'user' => $this->user));?>
				<?php endif;?>
			</td>	
			<td class="normal" style="width: 90px;">
				<a href="<?php echo $this->baseUrl('/assets/miniatures/'.$application->miniature)?>" 
					class="miniature"
					rel="application_<?php echo $application->application_id;?>" 
					title="<?php echo $application->user->getUserFullName();?>">
					<img src="<?php echo $this->baseUrl('/assets/miniatures/'.$application->miniature)?>" width="100px" height="100px" alt="thumbnail" />
				</a>
				</td>
			<td class="normal" style="width: 20px;"><?php echo ++$no;?></td>
			<td class="normal" style="width: 100px;">
				<a href="<?php echo $this->url(array('id' => $application->application_id, 'lang' => $this->lang), 'lang_application');?>">
					<?php echo $application->user->getUserFullName();?>
				</a>
			</td>
			<td class="normal" style="width: 20px;"><?php echo $this->translate($application->country);?></td>
			<td class="normal" style="width: 85px;"><?php echo $application->work_subject;?></td>
			<td class="normal" style="width: 35px;"><?php echo $application->work_type->work_type_name;?></td>
			<td class="normal" style="width: 50px;">
				<?php foreach($application->files as $id => $file):?>
				<a href="<?php echo $this->baseUrl('/assets/applications/'.$file->path);?>"
					class="application"
					rel="application_<?php echo $application->application_id;?>"
					title="<?php echo $file->file_desc;?>">
					<?php echo $this->translate('file').' '.++$id;?>, 
				</a>
				<?php endforeach;?>
			
			</td>
			
			<!-- VOTES -->
			<td class="normal" style="width: 90px;"></td>
			<td class="right" style="width: 40px;text-align:left;">	</td>
		</tr>
		<?php endforeach;?>
	</table>

	<table class="stats"> 
		<tr style="text-align: left;margin:0px; padding:0px;"> 
			<td class="header"><?php echo $this->translate('statistics');?></th> 
		</tr> 
		<tr>
			<th></th> 
			<?php foreach ($this->statistics['pl'] as $type => $ammount):?>
			<th><?php echo $this->translate($type);?></th>
			<?php endforeach;?> 
		</tr> 
		<?php foreach($this->statistics as $part => $stats):?>
		<tr>
			<td class="left"><?php echo $this->translate('stat_'.$part);?></td>
			<?php foreach ($stats as $type => $ammount):?>
			<td><?php echo $ammount;?></td>
			<?php endforeach;?>
		</tr>
		<?php endforeach;?>
	</table>
	<?php else:?>
	<p class="empty">
		<br />
		<?php echo $this->translate('no_applications');?>
		<br /><br /><br />
	</p>
		
	<?php endif;?>
</div>

<p class="spacer_small">&nbsp;</p> 
<p class="previous"><a href="<?php echo $this->baseUrl('/admin');?>">&lt; <?php echo $this->translate('previous_page');?></a></p>