<?php echo $this->partial('partials/delete_dialog.phtml',
array('title' => 'editions', 'delete_confirm' => $this->translate('application_delete_confirm')));
Zefir_Pqp_Classes_Console::logSpeed('start rendering');
$admin = $this->user->_role == 'admin' ? TRUE : FALSE;
$juror = $this->user->_role == 'juror' ? $this->user->juror : FALSE;
?>

<div id="main">
	<h1>

	<?php echo $this->translate('applications_header'); ?></h1>
	
	<?php if (count($this->applications) > 0):?>
	<p class="clear">&nbsp;</p>
	<div class="filter_applications">
		<div>
		<p><?php echo $this->translate('filter_applications')?></p>
		<form>
			<select>
				<option value="0" ><?php echo $this->translate('unrated')?></option>
				<option value="1" ><?php echo $this->translate('disqualified')?></option>
				<option value="2" ><?php echo $this->translate('qualified')?></option>
			</select>
		</form>
		</div>
		
		<div>
		<p><?php echo $this->translate('voting_stage');?></p>
		<form>
			<select>
				<?php foreach($this->stages as $stage):?>
				<option value="<?php echo $stage->stage_id;?>" ><?php echo $stage->stage_name?></option>
				<?php endforeach;?>
			</select>
		</form>
		</div>
	</div>
	<div class="clear"></div>
	<table class="applications">
		<!--TABLE HEADERS-->
		<tr class="header">
			<!--CHECKBOX FOR MANAGING-->
			<th class="left" style="width: 15px;">
				&nbsp;
			</th>			
			<!--ID-->	
			<th class="normal" style="width: 20px;">
				#
			</th>
			<!--UID-->
			<th class="left" style="width: 15px;">
				UID
			</th>
			<!--MINIATURE-->
			<th class="left" style="width: 80px;">
				<?php echo $this->translate('miniature');?>
			</th>
			<!--NAME-->
			<th class="normal" style="width: 70px;">
				<a href="<?php echo $this->url(array('sort' => 'surname'), 'applications_sort');?>">
				<?php echo $this->translate('user_name_and_surname');?>
				</a>
			</th>
			
			<!--COUNTRY-->
			<th class="normal" style="width: 20px;">
				<a href="<?php echo $this->url(array('sort' => 'country'), 'applications_sort');?>">
				<?php echo $this->translate('country');?>
				</a>
			</th>
			
			<!--2d/3d-->
			<th class="normal" style="width: 35px;">
				<a href="<?php echo $this->url(array('sort' => 'work_type_name'), 'applications_sort');?>">
				<?php echo $this->translate('work_type');?>
				</a>
			</th>
			
			<!--SUBJECT-->
			<th class="normal" style="width: 160px;">
				<a href="<?php echo $this->url(array('sort' => 'work_subject'), 'applications_sort');?>">
				<?php echo $this->translate('work_subject');?>
				</a>
			</th>
			
			
			<!--FILES LIST-->
			<th class="normal" style="width: 130px;">
				<?php echo $this->translate('application_files');?>
			</th>
			<!--VOTE LINK-->
			<th class="normal" style="width: 100px;">
				<?php echo $this->translate('vote');?>
			</th>
		</tr>
		<!--END OF TABLE HEADERS-->
		
		<!--APPLICATIONS DATA -->
		<?php foreach ($this->applications as $no => $application):?>
		<tr <?php if ($no%2 == 0):?>class="grey"<?php endif;?>>
			<!-- ADMIN ACTION -->
			<td class="left" style="width: 15px;vertical-align: top;">
				
				<?php if ($admin):?>
				<input type="checkbox" id="app<?php echo $application->application_id?>" name="app[<?php echo $application->application_id?>]" class="admin_button" />
				
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-check no-block"
					id="check_app<?php echo $application->application_id?>" 
					alt="<?php echo $this->translate('check');?>" 
					title="<?php echo $this->translate('check');?>"/>
				
				<?php echo $this->partial('applications/_admin.phtml', array('application' => $application, 'user' => $this->user));?>
				<?php endif;?>
				
			</td>	
			
			<!-- # -->
			<td class="normal" style="width: 20px;"><?php echo ++$no;?></td>
			
			<!-- UID -->
			<td class="normal" style="width: 15px;"><?php echo $application->application_id;?></td>
			
			<!-- MINIATURE -->
			<td class="left" style="width: 80px;">
				<img src="<?php echo $this->baseUrl('/assets/applications/'.$application->getMiniature()); ?>" 
					class="miniature" rel="application_<?php echo $application->application_id;?>"/>
			</td>
			<!-- USER -->
			<td class="normal" style="width: 70px;">
				<a href="<?php echo $this->url(array('id' => $application->application_id, 'lang' => $this->lang), 'lang_application');?>">
					<?php echo $application->user->name?><br />
					<span class="bold"><?php echo $application->user->surname ?></span>
				</a>
			</td>
			
			<!-- COUNTRY -->
			<td class="normal" style="width: 20px;"><?php echo $this->translate($application->country);?></td>
			
			<!-- WORK TYPE -->
			<td class="normal" style="width: 35px;"><?php echo $application->work_type->work_type_name;?></td>
			
			<!-- SUBJECT -->
			<td class="normal" style="width: 160px;"><?php echo $application->work_subject;?></td>
			
			
			<!-- FILES -->
			<td class="normal" style="width: 130px;">
				<?php foreach($application->files as $id => $file):?>
				<a href="<?php echo $this->baseUrl('/assets/applications/'.$file->path);?>"
					class="application_files index_application_files"
					rel="application_<?php echo $application->application_id;?>">
					<?php echo ++$id;?> 
				</a>
				<?php endforeach;?>
			
			</td>
			
			<!-- VOTES -->
			<td class="normal" style="width: 100px;">
				<?php if ($juror):?>
					<?php $vote = (int)$juror->getJurorVote($this->currentStage->stage_id, $application->application_id);?>
					
					<?php for($i = 0; $i <= $this->currentStage->stage_max_vote; $i++):?>
						<span class="vote <?php if ($i === $vote) echo 'voted_'.$i;?>"><?php echo $this->translate('vote_'.$i);?></span>
					<?php endfor;?>
					<p class="clear"></p>
				<?php elseif ($admin):?>
				
				<?php endif;?>
			</td>
		</tr>
		<?php endforeach;?>
	</table>

	<table class="stats"> 
		<tr class="header"> 
			<th colspan="5"><?php echo $this->translate('statistics');?></th> 
		</tr> 
		<tr>
			<th></th> 
			<?php foreach ($this->statistics['pl'] as $type => $ammount):?>
			<th><?php echo $this->translate($type);?></th>
			<?php endforeach;?> 
		</tr> 
		<?php foreach($this->statistics as $part => $stats):?>
		<tr>
			<td class="left"><?php echo $this->translate('stat_'.$part);?></td>
			<?php foreach ($stats as $type => $ammount):?>
			<td><?php echo $ammount;?></td>
			<?php endforeach;?>
		</tr>
		<?php endforeach;?>
	</table>
	<?php else:?>
	<p class="empty">
		<br />
		<?php echo $this->translate('no_applications');?>
		<br /><br /><br />
	</p>
		
	<?php endif;?>
</div>
