<?php 
$admin = $this->user->_role == 'admin' ? TRUE : FALSE;
$juror = $this->user->_role == 'juror' ? $this->user->juror : FALSE;

?>
<?php if ($juror != null || $admin): ?>
<div class="vote application_data vote_box" data-application-id="<?php echo $this->application->application_id;?>" 
		data-stage="<?php echo $this->currentStage->order?>">
	<h3><?php echo $this->translate('voting');?>
		<p>
			<?php foreach($this->stages as $stage):?>
			<span class="stage_choice <?php if ($stage->stage_id == $this->currentStage->stage_id) echo 'current';?>" data-stage="<?php echo $stage->order?>"><?php echo $stage->stage_name;?></span>
			<?php endforeach;?>
		</p>
	</h3>
	<p class="clear"></p>

	
	<?php if ($this->application->inStage($this->currentStage)): ?>	
	
	<?php if ($juror && $this->currentStage->active)  :?>
	<?php 
		$vote = $this->application->getJurorVote($this->currentStage->stage_id, $juror->juror_id);
		$vote = $vote != null ? (int)$vote : $vote;
	?>
	<p class="votes">
		<span style="float: left;width: 100px;"><?php echo $this->translate('your_vote');?>:</span>
	<?php for($i = 0; $i <= $this->currentStage->stage_max_vote; $i++):?>
		<?php
			$class = '';
			if (($i*$juror->wage) === $vote) 
			{
				if ($i == 0) $class = 'voted vote_first';
				elseif ($i == $this->currentStage->stage_max_vote) $class = 'voted vote_last';
				else $class = 'voted vote_'.$i;
			}
		?>
		<span class="vote <?php echo $class?>"
			data-juror-id="<?php echo $juror->juror_id?>" data-stage-id="<?php echo $this->currentStage->stage_id?>" 
			data-vote="<?php echo $i?>" data-application-id="<?php echo $this->application->application_id?>">
			<?php 
				if ($this->currentStage->translate)
				{
					 echo $this->translate('stage_'.$this->currentStage->order.'_vote_'.$i);
				}
				else 
				{
					echo $i;
				}
			?>
		</span>
	
	<?php endfor;?>
	</p>
	<p class="clear"></p>
	<?php elseif ($juror && $this->currentStage->active == 0):?>
	<p><?php echo $this->translate('stage_closed');?></p>
		
	<?php elseif ($admin):?>
		<!-- GET EACH JURORS VOTE -->
		<div class="application_votes">
		<?php foreach($this->votes[$this->application->application_id] as $juror_id =>  $juror_vote):?>
			<!-- CREATE FIELDS FOR VOTES FOR EACH JUROR-->
				<p class="votes">
					<span class="juror_name"><?php echo $juror_vote['juror_name']?>:</span>
					<?php for($i = 0; $i <= $this->currentStage->stage_max_vote; $i++):?>
						<?php
							$class = '';
							if (($i*$juror_vote['wage']) === $juror_vote['vote']) 
							{
								if ($i == 0) $class = 'voted vote_first';
								elseif ($i == $this->currentStage->stage_max_vote) $class = 'voted vote_last';
								else $class = 'voted vote_'.$i;
							}
						?>
						<span class="vote <?php echo $class;?>" 
								data-juror-id="<?php echo $juror_id?>" data-stage-id="<?php echo $this->currentStage->stage_id?>" 
								data-vote="<?php echo $i?>" data-application-id="<?php echo $this->application->application_id?>">
								<?php 
								if ($this->currentStage->translate)
								{
									 echo $this->translate('stage_'.$this->currentStage->order.'_vote_'.$i);
								}
								else 
								{
									echo $i;
								}										
								?>
						</span>
					<?php endfor;?>
				</p>					
				<p class="clear" style="height: 2px;"></p>	
		<?php endforeach;?>
		</div>
	<?php endif;?>
	
	<?php else: ?>
	
	<p><?php echo $this->translate('no_qualified');?></p>	
	
	<?php endif;?>
			
</div>
<?php endif;?>