<div id="main">

<?php if ($this->user->_role == 'admin'):?>
	<h1>
	<?php echo $this->translate('admin_panel');?></h1>
	
	
	<?php else:?>
	<h1><?php echo $this->translate('juror_panel');?></h1>
	<?php endif;?>	
	
	<br /><br />
	
	<a class="button_link" href="<?php echo $this->baseUrl('/applications')?>">
		<?php echo $this->translate('applications');?>
	</a><br />
	<?php if ($this->user->_role == 'admin'):?>
	<a class="button_link" href="<?php echo $this->baseUrl('/users')?>">
		<?php echo $this->translate('users');?>
	</a><br />
	<?php else:?>
	<a class="button_link" href="<?php echo $this->url(array('id' => $this->user->user_id), 'user');?>">
		<?php echo $this->translate('user_account');?>
	</a><br />
	<?php endif;?>
	<?php if ($this->user->_role == 'admin'):?>
	<a class="button_link" href="<?php echo $this->baseUrl('/editions')?>">
		<?php echo $this->translate('editions');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/work-types')?>">
		<?php echo $this->translate('work_types');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/schools')?>">
		<?php echo $this->translate('schools');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/languages')?>">
		<?php echo $this->translate('languages');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/captions')?>">
		<?php echo $this->translate('captions');?>
	</a><br />
	<?php endif;?>
	<a class="button_link" href="<?php echo $this->baseUrl('/localizations')?>">
		<?php echo $this->translate('localizations');?>
	</a><br />
	<?php if ($this->user->_role == 'admin'):?>
	<a class="button_link" href="<?php echo $this->baseUrl('/settings/edit')?>">
		<?php echo $this->translate('settings');?>
	</a><br />
	<?php endif;?>
	
</div>
