<div class="content">
	<h1><?php echo $this->translate('admin_panel');?></h1>	
	
	<br /><br />
	
	<a class="button_link" href="<?php echo $this->baseUrl('/applications')?>">
		<?php echo $this->translate('applications');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/users')?>">
		<?php echo $this->translate('users');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/editions')?>">
		<?php echo $this->translate('editions');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/work-types')?>">
		<?php echo $this->translate('work_types');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/schools')?>">
		<?php echo $this->translate('schools');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/localizations')?>">
		<?php echo $this->translate('localizations');?>
	</a><br />
	<a class="button_link" href="<?php echo $this->baseUrl('/settings/edit')?>">
		<?php echo $this->translate('settings');?>
	</a><br />
	
</div>
<p class="spacer_small">&nbsp;</p>
<p class="previous"><a href="/">&lt; <?php echo $this->translate('previous_page');?></a></p>