<p class="admin">
	<a href="<?php echo $this->url(array(), 'press_description');?>"> <img
		src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
		class="ui-icon ui-icon-document no-block"
		alt="<?php echo $this->translate('press_description');?>"
		title="<?php echo $this->translate('press_description');?>">
	</a>
	<a href="<?php echo $this->url(array(), 'new_press_element');?>">
		<img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
		class="ui-icon ui-icon-plusthick no-block"
		alt="<?php echo $this->translate('press_new');?>"
		title="<?php echo $this->translate('press_new');?>">
	</a> 
</p>
