<div id="main">
	<?php if ($this->user->role == 'admin') echo $this->partial('press/_admin.phtml', array('lang' => $this->lang));?>
	
	<h1><?php echo $this->translate('press_header');?></h1>
	
	<p class="spacer">&nbsp;</p>
	<div class="press_wrapper">
		<?php foreach($this->press['file'] as $element):?>
		<div class="press_element">
			<span class="file_description"><?php echo $element->element_description;?>:</span>
			<?php foreach($element->files as $file):?>
			<p class="press_link_wrap">
				<a href="<?php echo $file->getPath();?>" class="press_file"><?php echo strtoupper(Zefir_Filter::getExtension($file->path));?></a>
				<?php if ($this->user->role == 'admin') :?>
				<span class="file_remove" data-press-file-id="<?php echo $file->press_file_id;?>">x</span>
				<?php endif;?>
			</p>
			<?php endforeach;?>
			<?php if ($this->user->role == 'admin'):?>
			<a href="<?php echo $this->url(array(), 'new_press_element');?>" class="press_edit">+</a>
			<?php endif?>
		</div> 
		<?php endforeach;?>
	</div>
</div>