<?php echo $this->partial('partials/lang_menu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'link' => 'settings/edit',
						'lang' => $this->lang));
?>

<div class="content">
	<h1><?php echo $this->translate('settings');?></h1>
	
	<?php if ($this->form->csrf->hasErrors()):?>
	<div id="error-csrf" class="error-div">
		<p class="error"><?php echo $this->translate('csrf_error')?></p>
	</div>
	<?php endif;?>
	
	<?php echo $this->form;?>
	
	
	
	<p class="clear"></p>
</div>