<nav>
	<menu> 
		<p class="menu_label"><?php echo $this->translate('admin_panel')?> <span>&rsaquo;</span></p>
		<menu>
			<a href="<?php echo $this->url(array('sort' => 'surname'), 'applications_sort')?>"><?php echo $this->translate('applications');?></a>
			<a href="<?php echo $this->url(array(), 'users')?>"><?php echo $this->translate('users');?></a>
			<a href="<?php echo $this->url(array(), 'editions')?>"><?php echo $this->translate('editions');?></a>
			<a href="<?php echo $this->url(array(), 'types');?>"><?php echo $this->translate('work_types');?></a>
			<a href="<?php echo $this->url(array(), 'schools');?>"><?php echo $this->translate('schools');?></a>
			<a href="<?php echo $this->url(array(), 'languages');?>"><?php echo $this->translate('languages');?></a>
			<a href="<?php echo $this->url(array(), 'captions');?>"><?php echo $this->translate('captions');?></a>
			<a href="<?php echo $this->url(array('loc_lang' => $this->lang), 'localization');?>"><?php echo $this->translate('translations_link');?></a>
			<a href="<?php echo $this->url(array(), 'settings')?>"><?php echo $this->translate('settings');?></a>
		</menu>
	</menu>
</nav>