<nav>
	<menu> 
		<p class="menu_label"><?php echo $this->translate('edition').' '.str_replace('/', '-', $this->edition);?><span>&rsaquo;</span></p>
		<menu> 
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'about')?>"><?php echo $this->translate('about_link');?></a> 
			<a href="<?php echo $this->url(array(), 'news')?>"><?php echo $this->translate('news_link');?></a> 
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'lang_regulation')?>"><?php echo $this->translate('regulation_link');?></a> 
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'lang_application_new')?>"><?php echo $this->translate('form_link');?></a> 
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'lang_faq')?>""><?php echo $this->translate('faq_link');?></a> 
			<a class="nieaktywna" href="#"><s><?php echo $this->translate('best_works_link');?></s></a> 
			<a href="#"><?php echo $this->translate('press_link');?></a> 
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'contact')?>"><?php echo $this->translate('contact_link');?></a> 
		</menu>
	</menu>
</nav>