<nav>
	<menu>
		<p class="menu_label">
		<?php echo $this->translate('edition').' '.str_replace('/', '-', $this->edition);?>
			<span>&rsaquo;</span>
		</p>
		<menu>
			<?php if (($this->showResults()) || $this->user->role == 'admin'):?>
			<a href="<?php echo $this->url(array(), 'results')?>"><?php echo $this->translate('best_works_link');?></a>
			<?php endif;?> 
			
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'about')?>"><?php echo $this->translate('about_link');?></a>
			
			<a href="<?php echo $this->url(array(), 'news')?>"><?php echo $this->translate('news_link');?></a>
			
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'lang_regulation')?>"><?php echo $this->translate('regulation_link');?></a>

			<!-- NEW APPLICATION FOR NOT LOGGED USER-->
			
			
			<?php if ($this->user->role != 'user'):?>			 
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'lang_application_new')?>"><?php echo $this->translate('form_link');?></a> 
			<?php endif; ?>

			<a href="<?php echo $this->url(array('lang' => $this->lang), 'lang_faq')?>"><?php echo $this->translate('faq_link');?></a> 

			<?php if ($this->user->role == 'admin'):?>
			<a href="<?php echo $this->url(array(), 'press');?>"><?php echo $this->translate('press_link');?></a>
			<?php endif;?>
			 
			<a href="<?php echo $this->url(array('lang' => $this->lang), 'contact')?>"><?php echo $this->translate('contact_link');?></a>
			<?php if ($this->user->role == 'guest'):?>
				<a href="<?php echo $this->url(array(), 'login')?>"><?php echo $this->translate('login_link');?></a>
			<?php else:?>
				<a href="<?php echo $this->url(array(), 'logout')?>"><?php echo $this->translate('logout_link');?></a>
			<?php endif;?> 
		</menu>
	</menu>
</nav>
