<nav>
	<menu>
		<p class="menu_label">
		<?php echo $this->translate('admin_panel')?>
			<span>&rsaquo;</span>
		</p>
		<menu>
			<a
				href="<?php echo $this->url(array(), 'applications')?>"><?php echo $this->translate('applications');?>
			</a>
			<a
				href="<?php echo $this->url(array('id' => $this->user->user_id), 'user')?>"><?php echo $this->translate('account');?>
			</a>
			<a href="<?php echo $this->url(array(), 'schools');?>"><?php echo $this->translate('schools');?>
			</a>
			<a href="<?php echo $this->url(array(), 'captions');?>"><?php echo $this->translate('captions');?>
			</a>
			<a
				href="<?php echo $this->url(array('loc_lang' => $this->lang), 'localization');?>"><?php echo $this->translate('translations_link');?>
			</a>

		</menu>
	</menu>
</nav>
