<p class="language_bar"> 
		<a href="<?php echo $this->baseUrl.'cz/'.$this->link;?>"
		<?php if ($this->lang == 'cz'):?> style="color: red;font-weight: bold;"<?php endif;?>>CZ</a> |
		<a href="<?php echo $this->baseUrl.'pl/'.$this->link;?>" 
		<?php if ($this->lang == 'pl'):?> style="color: red;font-weight: bold;"<?php endif;?>>PL</a> |
		<a href="<?php echo $this->baseUrl.'sk/'.$this->link;?>" 
		<?php if ($this->lang == 'sk'):?> style="color: red;font-weight: bold;"<?php endif;?>>SK</a> 
</p>