<nav class="navi-lang">
	<a href="<?php echo $this->baseUrl('cs/'.$this->link);?>"
		class="lang <?php if ($this->lang == 'cs'):?>lang-selected<?php endif;?>">CZ</a>
	<a href="<?php echo $this->baseUrl('hu/'.$this->link);?>"
		class="lang <?php if ($this->lang == 'hu'):?>lang-selected<?php endif;?>">HU</a>
	<a href="<?php echo $this->baseUrl('pl/'.$this->link);?>"
		class="lang <?php if ($this->lang == 'pl'):?>lang-selected<?php endif;?>">PL</a>
	<a href="<?php echo $this->baseUrl('sk/'.$this->link);?>"
		class="lang <?php if ($this->lang == 'sk'):?>lang-selected<?php endif;?>">SK</a>
	<a href="<?php echo $this->baseUrl('en/'.$this->link);?>"
		class="lang <?php if ($this->lang == 'en'):?>lang-selected<?php endif;?>">EN</a>
</nav>
