<p class="login_form">
	<?php if ($this->user->_role != 'guest'):?>
	<?php echo $this->translate('logged_as')?>: <?php echo $this->translate($this->user->_role);?>
	&nbsp;|&nbsp;
	<a href="<?php echo $this->url(array(), 'logout');?>">
		<?php echo $this->translate('logout')?>
	</a>
	<?php else:?>
	<?php echo $this->translate('not_logged')?>
	&nbsp;|&nbsp;
	<a href="<?php echo $this->url(array(), 'login');?>">
		<?php echo $this->translate('login')?>
	</a>
	<?php endif;?>
</p>