<nav>
	<menu>
		<p class="menu_label">
		<?php echo $this->translate('user_panel')?>
			<span>&rsaquo;</span>
		</p>
		<menu>		
			<a href="<?php echo $this->url(array('id' => $this->user->user_id), 'user')?>">
				<?php echo $this->translate('my_account');?>
			</a>			
			<a href="<?php echo $this->url(array('id' => $this->user->applications[0]->application_id), 'application')?>">
				<?php echo $this->translate('show_user_application');?>
			</a>
		</menu>
	</menu>
</nav>
