<div id="main">


<?php foreach($this->diplomas as $id => $diploma):?>

	<div class="diploma">
		<a
			href="<?php echo $this->url(array('lang' => $this->lang, 'slug' => $diploma->slug, 'edition' => $this->edition_name), 'lang_slug_project');?>">
			<img
			src="<?php echo $this->baseUrl('assets/editions/'.$diploma->getFirstFile()->getImage('thumb'));?>"
			alt="" style="width: 100%;" />
		</a>
		<p class="index_author">
			<a
				href="<?php echo $this->url(array('lang' => $this->lang, 'slug' => $diploma->slug, 'edition' => $this->edition_name), 'lang_slug_project');?>">
				<?php echo $diploma->getAuthorName();?> <span class="country">(<?php echo strtoupper($diploma->country);?>)
			</span> </a>
		</p>
		<p>
		<?php  echo $diploma->getField('work_subject', $this->lang);?></p>

	</div>
	
	
		<?php if (++$id % 4 == 0 or ($id) == count($this->diplomas)): ?>
	 	<!-- every 4 diplomas-->
		<p class="clearfix"></p>
		<?php endif;?>
	<?php endforeach;?>	

</div>
