<?php echo $this->partial('partials/lang_menu.phtml',
array('link' => 'editions/new', 'lang' => $this->lang));
?>
<div class="content">
	<h1>

	<?php echo $this->translate('new_edition');?></h1>
	
	
	
	
	<?php echo $this->form;?>
</div>

<p class="spacer_small">&nbsp;</p>
<p class="previous">
	<a href="<?php echo $this->baseUrl('/admin');?>"> &lt; <?php echo $this->translate('previous_page');?>
	</a>
</p>
