<div id="main">

	<div class="diploma_gallery" id="diploma_gallery">

	<?php foreach($this->diploma->files as $file):?>
	<div id="<?php echo $file->file_id?>">
	<?php if ($this->user->role == 'admin'):?>
	<p class="admin removeProjectImage">
		
		<img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
			class="ui-icon ui-icon-arrow-4 no-block enable-sort"
			alt="<?php echo $this->translate('move');?>"
			title="<?php echo $this->translate('move');?>">
		<a
			href="<?php echo $this->url(array('id' => $file->file_id), 'diploma_image_delete');?>"
			class="delete"> <img
			src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
			class="ui-icon ui-icon-trash no-block"
			alt="<?php echo $this->translate('delete');?>"
			title="<?php echo $this->translate('delete');?>">
		</a>
	</p>
	<?php endif;?>
	<a href="<?php echo $this->baseUrl('/assets/editions/'. $file->path);?>"
			class="application_files" rel="images" >
		<img class="sort_item"
			src="<?php echo $this->baseUrl('assets/editions/'.$file->getImage('small'));?>"
			alt="<?php echo $this->diploma->getField('work_subject', $this->lang);?>"
			class="diploma_image" />
	</a>		
	</div>
	<p class="clear">&nbsp;</p>		
	<?php endforeach;?>
	</div>

	<div class="dyplom" id="<?php echo $this->diploma->diploma_id?>">

	<?php if ($this->user->role == 'admin' || $this->user->role == 'juror'):?>
		<p class="admin">
			<a
				href="<?php echo $this->url(array('lang' => $this->lang, 'id' => $this->diploma->diploma_id), 'lang_edit_project');?>">
				<img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
				class="ui-icon ui-icon-pencil no-block"
				alt="<?php echo $this->translate('edit');?>"
				title="<?php echo $this->translate('edit');?>">
			</a>
      <a
        href="<?php echo $this->url(array('lang' => $this->lang, 'id' => $this->diploma->diploma_id), 'lang_delete_project');?>">
        <img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
        class="ui-icon ui-icon-trash no-block"
        alt="<?php echo $this->translate('delete');?>"
        title="<?php echo $this->translate('delete');?>">
      </a>

		</p>
		
		
		<?php endif?>
		<p class="diploma_field"><?php echo strtolower($this->translate('edition'));?></p>
		<p class="diploma_data diploma_edition"><?php echo $this->diploma->edition->edition_name;?>
			<?php if ($this->diploma->edition->edition_name < '2009–2010'):?>
			<span class="kraj">(<?php echo $this->translate('only_polish_edition');?>)</span>
			<?php endif;?>
		</p>

		<p class="diploma_field"><?php echo strtolower($this->translate('title'));?></p>
		<p class="diploma_data"><?php echo $this->diploma->getField('work_subject', $this->lang);?></p>
		<p class="clearfix" ></p>
		<p class="diploma_field"><?php echo strtolower($this->translate('author'));?></p>
		<p class="diploma_data">
			<span class="author"><?php echo $this->diploma->getAuthorName();?>
				<span class="country">(<?php echo strtoupper($this->diploma->country);?>)</span>
			</span>
		</p>
		
		<?php if ($this->diploma->email != null && $this->diploma->show_email == 1):?>
		<p class="diploma_field"><?php echo strtolower($this->translate('e-mail'));?></p>
		<p class="diploma_data"><?php echo $this->diploma->email;?></p>
		<?php endif;?>

    <?php if ($this->diploma->author_portfolio != null):?>
    <p class="diploma_field"><?php echo strtolower($this->translate('author_portfolio'));?></p>
    <p class="diploma_data"><a href="<?php echo $this->diploma->author_portfolio;?>"><?php echo $this->diploma->author_portfolio;?></a></p>
    <?php endif;?>

    <?php if ($this->diploma->work_site != null):?>
    <p class="diploma_field"><?php echo strtolower($this->translate('work_site'));?></p>
    <p class="diploma_data"><a href="<?php echo $this->diploma->work_site;?>"><?php echo $this->diploma->work_site;?></a></p>
    <?php endif;?>
		
		<?php if ($this->diploma->degree->degree_name != null):?>
		<p class="diploma_field"><?php echo strtolower($this->translate('degree'));?></p>
		<p class="diploma_data"><?php echo $this->translate($this->diploma->degree->degree_name.'_adjective');?></p>
		<?php endif;?>
		
		<p class="diploma_field"><?php echo strtolower($this->translate('school'));?></p>
		<p class="diploma_data"><?php echo $this->diploma->getField('school', $this->lang);?></p>
		
		<?php if ($this->diploma->getField('department', $this->lang) != ''):?>
		<p class="diploma_field"><?php //echo strtolower($this->translate('department'));?></p>
		<p class="diploma_data"><?php echo $this->diploma->getField('department', $this->lang);?></p>
		<?php endif; ?>
		<p class="diploma_field"><?php echo strtolower($this->translate('supervisor'));?></p>
		<p class="diploma_data"><?php echo $this->diploma->getSupervisor();?></p>
		
		<div class="work_desc">
			<p><?php echo nl2br($this->diploma->getField('work_desc', $this->lang));?></p>
		</div>
		
		<nav class="diploma_nav">
			
			<a href="<?php echo $this->url(array('slug' => $this->adjacent['previous']->slug, 'lang' => $this->lang, 'edition' => $this->diploma->edition->edition_name), 'lang_slug_project');?>" class="wiecej"><img src="<?php echo $this->baseUrl('img/simple/bullet-back.png')?>" /></a>
			<a href="<?php echo $this->url(array('slug' => $this->adjacent['next']->slug, 'lang' => $this->lang, 'edition' => $this->diploma->edition->edition_name), 'lang_slug_project');?>" class="wiecej"><img src="<?php echo $this->baseUrl('img/simple/bullet-forward.png')?>" /></a>
			
		</nav>
    </div>

</div>
<?php if ($this->user->role == 'admin'):?>
<?php echo $this->partial('partials/delete_dialog.phtml',
array('title' => 'file', 'delete_confirm' => $this->translate('application_image_delete_confirm')));
?>
<?php endif;?>