<?php $form = $this->element;?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
      method="<?php echo $this->escape($form->getMethod()); ?>"
      enctype="<?php echo $form->getEnctype(); ?>"
      class="contact">

	<?php if ($form->csrf->hasErrors()):?>
		<div id="error-csrf" class="error-div">
			<p class="error"><?php echo $this->translate('csrf_error')?></p>
		</div>
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?> 
	<?php echo $form->lang_code;?>
	<?php echo $form->name;?>
	
	<?php echo $form->text;?>

	<p class="submit center">
		<?php echo $form->submit; ?>
		<?php echo $form->leave; ?>
	</p>
		
</form>