<?php $form = $this->element;
$appSettings = Zend_Registry::get('appSettings');
?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
	method="<?php echo $this->escape($form->getMethod()); ?>"
	enctype="<?php echo $form->getEnctype(); ?>" class="contact"
	id="applicationForm">


	<?php if ($form->csrf->hasErrors()):?>
	<div id="error-csrf" class="error-div">
		<p class="error">
			
		<?php echo $this->translate('csrf_error')?></p>
	</div>
	
	
	
	
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?>
	<?php echo $form->application_id; ?>  
	<?php echo $form->edition_id; ?>
	<?php echo $form->user_id; ?>
	
	<div class="column-left">
	  
		<?php echo $form->country;?>
		
		<?php echo $form->school;?>
		
		<?php echo $form->department;?>
		
		<?php echo $form->degree_id;?>
		
		<?php echo $form->work_subject;?>
		
		<?php echo $form->work_type_id;?>
		
		<p class="label"><?php echo $this->translate($form->work_desc->getLabel());?>:&nbsp;
		<span style="color: #987878;"><?php echo $this->translate($form->work_desc->getDescription());?></span>
		</p>
		<?php echo $form->work_desc->renderTextField();?>
		<?php echo $form->work_desc->renderErrorMsg();?>
		<p id="word_count"><?php echo $this->translate('counter');?>: <span id="word_counter">0</span></p>
		
		<?php echo $form->supervisor_degree;?>
		<?php echo $form->supervisor;?>
		
		<?php echo $form->graduation_time;?>
	</div>
	
	<div class="column-right">
	<p style="margin: 30px 0px 0px 0px;">
		<?php echo $this->translate('files_info')?><br />
		<?php echo $this->translate('max_files')?>: <?php echo $appSettings->max_files;?><br />
		<?php echo $this->translate('max_file_size')?>: <?php echo ($appSettings->max_file_size/1024/1024);?>mb<br />
	</p>
	
	<div id="app_images">
		<?php for ($i = 1; $i <= $appSettings->max_files; $i++): ?> 
			<?php 
				$file = $form->getSubForm('file_'.$i);
				$cache = 'file_'.$i.'Cache';
			 	if ($file->$cache->getValue() != null):?>
			<div id="file_<?php echo $file->file_id->getValue()?>" style="width: 460px;">
		 	<p class="admin editApplication">
		 		<a href="<?php echo $this->url(array('id'=> $file->file_id->getValue()), 'applications_image_delete');?>"
					class="remove-image" alt="file_<?php echo $i;?>">
					<img src="<?php echo $this->baseUrl('img/simple/empty.png');?>" class="ui-icon ui-icon-trash no-block" 
						alt="<?php echo $this->translate('delete');?>" 
						title="<?php echo $this->translate('delete');?>">
				</a>
			</p>
			<a 	class="form_file"
				href="<?php echo $this->baseUrl('/assets/'.$file->$cache->getValue());?>"
				rel="cache" >
				<img src="<?php echo $this->baseUrl('/assets/'.$file->$cache->getValue());?>" alt="" />
			</a>
			</div>
			<?php endif;?>
			<p class="clearfix"></p>
		<?php endfor;?>
	</div>
	<?php for ($i = 1; $i <= $appSettings->max_files; $i++) 
			echo $form->getSubForm('file_'.$i);
	?>
	</div>
	
	<p class="clearfix"></p>
	<fieldset class="submit">
		<p class="submit center">
			<?php echo $form->leave; ?>
			<?php echo $form->submit; ?>
		</p>
	</fieldset>
</form>
