<?php $form = $this->element; ?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
      method="<?php echo $this->escape($form->getMethod()); ?>"
      enctype="<?php echo $form->getEnctype(); ?>"
      class="contact">

	<?php if ($form->csrf->hasErrors()):?>
		<div id="error-csrf" class="error-div">
			<p class="error"><?php echo $this->translate('csrf_error')?></p>
		</div>
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?> 
	<?php echo $form->edition;?>
	
	<?php echo $form->nick;?>
	<?php echo $form->password;?>
	<?php echo $form->password_check;?>

	<?php echo $form->country;?>
	
	<?php echo $form->name;?>
	
	<?php echo $form->surname;?>
	
	<?php echo $form->address;?>
	
	<?php echo $form->phone;?>
	
	<?php echo $form->email;?>
	<?php echo $form->show_email;?>
	
	<?php echo $form->email_repeat;?>
	
	<?php echo $form->school;?>
	<?php echo $form->new_school;?>
	
	<?php echo $form->department;?>
	
	<?php echo $form->degree;?>
	
	<?php echo $form->work_subject;?>
	
	<?php echo $form->work_type;?>
	
	<p class="label"><?php echo $this->translate($form->work_desc->getLabel());?>:&nbsp;
	<span style="color: #987878;"><?php echo $this->translate($form->work_desc->getDescription());?></span>
	</p>
	<?php echo $form->work_desc->renderTextField();?>
	<?php echo $form->work_desc->renderErrorMsg();?>
	<p id="word_count"><?php echo $this->translate('counter');?>: <span id="word_counter">0</span></p>
	
	<?php echo $form->supervisor_degree;?>
	<?php echo $form->supervisor;?>
	
	<?php echo $form->graduation_time;?>
	
	<?php echo $form->miniature;?>
	
	<?php echo $form->personal_data_agreement;?>

	<p class="submit center">
		<?php echo $form->submit; ?>
	</p>
		
</form>