<?php $form = $this->element; 
	$appSettings = Zend_Registry::get('appSettings');
?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
      method="<?php echo $this->escape($form->getMethod()); ?>"
      enctype="<?php echo $form->getEnctype(); ?>"
      class="contact">

	<?php if ($form->csrf->hasErrors()):?>
		<p class="spacer">&nbsp;</p>
		<div id="error-csrf" class="error-div">
			<p class="error"><?php echo $this->translate('csrf_error')?></p>
		</div>
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?> 
	<?php echo $form->edition;?>
	
	<?php echo $form->getSubForm('user');?>
		
	<?php echo $form->country;?>
	
	<?php echo $form->school;?>
	<?php echo $form->new_school;?>
	
	<?php echo $form->department;?>
	
	<?php echo $form->degree;?>
	
	<?php echo $form->work_subject;?>
	
	<?php echo $form->work_type;?>
	
	<p class="label"><?php echo $this->translate($form->work_desc->getLabel());?>:&nbsp;
	<span style="color: #987878;"><?php echo $this->translate($form->work_desc->getDescription());?></span>
	</p>
	<?php echo $form->work_desc->renderTextField();?>
	<?php echo $form->work_desc->renderErrorMsg();?>
	<p id="word_count"><?php echo $this->translate('counter');?>: <span id="word_counter">0</span></p>
	
	<?php echo $form->supervisor_degree;?>
	<?php echo $form->supervisor;?>
	
	<?php echo $form->graduation_time;?>
	
	<?php if ($form->miniatureCache->getValue() != null): ?>
	<p class="label"><?php echo $this->translate('miniature');?></p>
	<img src="<?php echo $this->baseUrl('/assets/'.$form->miniatureCache->getValue());?>" 
		width="300" height="300"/>
	<?php endif;?>
	<?php echo $form->miniatureCache;?>
	<?php echo $form->miniature;?>
	<p class="clear">&nbsp;</p>
	<p style="margin: 30px 0px 0px 0px;">
		<?php echo $this->translate('files_info')?><br />
		<?php echo $this->translate('max_files')?>: <?php echo $appSettings->_max_files;?><br />
		<?php echo $this->translate('max_file_size')?>: <?php echo ($appSettings->_max_file_size/1024/1024);?>mb<br />
	</p>
	<?php for ($i = 1; $i <= $appSettings->_max_files; $i++) 
			echo $form->getSubForm('file_'.$i);
	?>
	
	<p class="clear">&nbsp;</p>
	
	<?php echo $form->personal_data_agreement;?>

	<fieldset class="submit">
		<p class="submit center">
			<?php echo $form->submit; ?>
			<?php echo $form->leave; ?>
		</p>
	</fieldset>
		
</form>