<?php $form = $this->element; ?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
	method="<?php echo $this->escape($form->getMethod()); ?>"
	class="contact">



	<?php if ($form->csrf->hasErrors()):?>
	<div id="error-csrf" class="error-div">
		<p class="error">
			
		<?php echo $this->translate('csrf_error')?></p>
	</div>
	
	
	
	
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?> 

	<?php echo $form->name;?>
	
	<?php echo $form->email;?>

	<?php echo $form->mail_title;?>
	
	<p class="label"><?php echo $this->translate($form->mail_text->getLabel());?>&nbsp;
	<span style="color: #000;font-weight: normal;"><?php echo $this->translate('mail_text_count');?></span>
	</p>
	<?php echo $form->mail_text->renderTextField();?>
	<?php echo $form->mail_text->renderErrorMsg();?>
	<p id="word_count"><?php echo $this->translate('counter');?>: <span id="word_counter">0</span></p>
	
	<fieldset class="submit">
		<p class="submit center">
			<?php echo $form->submit; ?>
		</p>
	</fieldset>
		
</form>
