<?php 	$form = $this->element;
		$file = 'file_'.$this->number;
		$cache = $file.'Cache'; 
		$appSettings = Zend_Registry::get('appSettings');
?>
<fieldset class="fileFieldset <?php if ($form->$file->hasErrors()) echo 'error';?>">
	<legend><?php echo $this->translate('file').' '.$this->number;?></legend	>
	
	<?php echo $form->$cache;?>
	<?php echo $form->application_id;?>
	<?php echo $form->file_id;?>
	<?php if ($form->$cache->getValue() == null) {
		echo $form->$file->renderFile();
	}?>
	
</fieldset>
<?php if ($form->$file->hasErrors()){ echo $form->$file->renderErrorMsg(); }?>
