<?php $form = $this->element; 
	$appSettings = Zend_Registry::get('appSettings');
?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
      method="<?php echo $this->escape($form->getMethod()); ?>"
      enctype="<?php echo $form->getEnctype(); ?>"
      class="contact">

	<?php if ($form->csrf->hasErrors()):?>
		<p class="spacer">&nbsp;</p>
		<div id="error-csrf" class="error-div">
			<p class="error"><?php echo $this->translate('csrf_error')?></p>
		</div>
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?>
	<?php echo $form->files ?>
	
	<ul class="lang_choice">
		<span><?php echo $this->translate('choose_language')?>: </span>
		<?php foreach($form->getLanguages() as $lang):?>
			<li class="choice_<?php echo $lang->lang_code;?>"><?php echo $lang->lang_code;?></li>
		<?php endforeach;?>
		
	</ul> 
	
	<?php echo $form->news_id ?>
	
	<?php echo $form->published; ?>
	
	<?php echo $form->link; ?>
	
	<?php foreach($form->getLanguages() as $lang):?>
	<div id="<?php echo $lang->lang_code?>" class="lang_div">
		<?php echo $form->getSubForm($lang->lang_code);?>	
	</div>
	<?php endforeach;?>
	
	<fieldset class="submit">
		<p class="submit center">
			<?php echo $form->leave; ?>
			<?php echo $form->submit; ?>
		</p>
	</fieldset>
		
</form>