<?php $form = $this->element;?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
	method="<?php echo $this->escape($form->getMethod()); ?>"
	enctype="<?php echo $form->getEnctype(); ?>"
	class="contact">

	<?php if ($form->csrf->hasErrors()):?>
	<div id="error-csrf" class="error-div">
		<p class="error">
			
		<?php echo $this->translate('csrf_error')?></p>
	</div>
	
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?>
	<?php echo $form->element_description; ?>
	<?php echo $form->element_path; ?>
	
	<p><a href="#" class="press_file"><?php echo $this->translate('add_file')?></a></p>
	 
	<fieldset class="submit">
		<p class="submit center">
			<?php echo $form->leave; ?>
			<?php echo $form->submit; ?>
		</p>
	</fieldset>
		
</form>
