<?php $form = $this->element;?>

<form action="<?php echo $this->escape($form->getAction()); ?>"
      method="<?php echo $this->escape($form->getMethod()); ?>"
      enctype="<?php echo $form->getEnctype(); ?>"
      class="contact">

	<?php if ($form->csrf->hasErrors()):?>
		<div id="error-csrf" class="error-div">
			<p class="error"><?php echo $this->translate('csrf_error')?></p>
		</div>
	<?php endif;?>
	<?php echo $form->csrf->renderViewHelper(); ?> 
	
	<p class="label">
		<?php echo $form->getElement('text')->getLabel();?> (<?php echo $form->data['lang']?>): 
		<span style="font-weight: normal; font-size: 14px"><?php echo $form->getElement('text')->getDescription();?></span>
	</p>
	<?php echo $form->text->renderTextField();?>
	
	<fieldset id="fieldset-submitFields" class="submit">
		<p class="submit center">
			<?php echo $form->leave; ?>
			<?php echo $form->submit; ?>
		</p>
	</fieldset>
		
</form>