<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'editions', 'delete_confirm' => $this->translate('edition_delete_confirm')));
?>

<div id="main">
	<h1><?php echo $this->translate('editions');?></h1>
	<br />
	<?php foreach ($this->editions as $id => $edition):?>
	<p>
		<span class="admin">
			<a href="<?php echo $this->url(array('id' => $id), 'edit_edition');?>">
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-pencil no-block" 
					alt="<?php echo $this->translate('edit');?>" 
					title="<?php echo $this->translate('edit');?>" />
			</a>
			<a href="<?php echo $this->url(array('id' => $id), 'archive_edition');?>"> 
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-disk no-block" 
					del="<?php echo $this->translate('archive');?>" 
					alt="<?php echo $this->translate('archive');?>" 
					title="<?php echo $this->translate('archive');?>" />
			</a>
			<a href="<?php echo $this->url(array('id' => $id), 'delete_edition');?>"
				class="delete"> 
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-trash no-block" 
					del="<?php echo $this->translate('delete');?>" 
					alt="<?php echo $this->translate('delete');?>" 
					title="<?php echo $this->translate('delete');?>" />
			</a>		
		</span>
		
		<span><?php echo $edition;?></span>
	</p>
	
	<?php endforeach;?>

</div>
