<br />
<?php echo $this->partial('partials/lang_menu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'link' => 'about',
						'lang' => $this->lang));
?>

<div class="content">
	<?php echo $this->partial('about/_admin.phtml');?>
	<h1><?php echo $this->translate('about_header');?></h1>
	<p class="spacer">&nbsp;</p>
	 
	<?php foreach ($this->about as $text):?>
	<p class="about">
		<?php echo $text;?>
	</p>
	<?php endforeach;?>
	
</div>	
<?php echo $this->partial('partials/submenu.phtml', 
			array(	'baseUrl' => $this->baseUrl));
?>

<p class="spacer_small">&nbsp;</p> 
<p class="previous"><a href="<?php echo $this->baseUrl;?>">&lt; <?php echo $this->translate('previous_page');?></a></p>
