<p class="language_bar"> 
		<a href="<?php echo $this->baseUrl('localizations/cs');?>"
		<?php if ($this->caption_lang == 'cs'):?> style="color: red;font-weight: bold;"<?php endif;?>>CZ</a> |
		<a href="<?php echo $this->baseUrl('localizations/pl');?>" 
		<?php if ($this->caption_lang == 'pl'):?> style="color: red;font-weight: bold;"<?php endif;?>>PL</a> |
		<a href="<?php echo $this->baseUrl('localizations/sk');?>" 
		<?php if ($this->caption_lang == 'sk'):?> style="color: red;font-weight: bold;"<?php endif;?>>SK</a> 
</p>
<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'localization', 'delete_confirm' => $this->translate('localization_delete_confirm')));
?>

<div class="content">
	<h1><?php echo $this->translate('localizations_header'); ?></h1>
	<?php echo $this->form;?>
</div>

