<p class="language_bar"> 
		<a href="<?php echo $this->baseUrl('localizations/cs');?>"
		<?php if ($this->caption_lang == 'cs'):?> style="color: red;font-weight: bold;"<?php endif;?>>CZ</a> |
		<a href="<?php echo $this->baseUrl('localizations/pl');?>" 
		<?php if ($this->caption_lang == 'pl'):?> style="color: red;font-weight: bold;"<?php endif;?>>PL</a> |
		<a href="<?php echo $this->baseUrl('localizations/sk');?>" 
		<?php if ($this->caption_lang == 'sk'):?> style="color: red;font-weight: bold;"<?php endif;?>>SK</a> 
</p>
<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'localization', 'delete_confirm' => $this->translate('localization_delete_confirm')));
?>

<div class="content">
	<h1><?php echo $this->translate('localizations_header'); ?>
	<a href="<?php echo $this->url(array(), 'new_caption');?>">
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-plusthick no-block" 
					alt="<?php echo $this->translate('new_caption');?>" 
					title="<?php echo $this->translate('new_caption');?>" />
			</a>
	</h1>
	<table class="localizations">
	<?php foreach ($this->captions as $caption):?>
	<tr>
		<td><?php echo $caption->name;?></td>
		
		<td><?php echo $caption->translate($caption->name, $this->caption_lang);?></td>
		
		<td style="width: 50px;padding: 5px;border-right:0px;">
			<span class="admin">
			<a href="<?php echo $this->url(array('id' => $caption->caption_id, 'loc_lang' => $this->caption_lang), 'edit_localization');?>">
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-pencil no-block" 
					alt="<?php echo $this->translate('edit');?>" 
					title="<?php echo $this->translate('edit');?>" />
			</a>
			<a href="<?php echo $this->url(array('id' => $caption->caption_id, 'loc_lang' => $this->caption_lang), 'delete_localization');?>"
				class="delete"> 
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-trash no-block" 
					del="<?php echo $this->translate('delete');?>" 
					alt="<?php echo $this->translate('delete');?>" 
					title="<?php echo $this->translate('delete');?>" />
			</a>
			
			</span>
		</td>
	</tr>
	<?php endforeach;?>
	</table>
</div>

