<div id="main">
	<h1><?php echo $this->translate('localizations_header'); ?>
	<a href="<?php echo $this->url(array(), 'new_caption');?>">
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-plusthick no-block" 
					alt="<?php echo $this->translate('new_caption');?>" 
					title="<?php echo $this->translate('new_caption');?>" />
			</a>
	</h1>
	<table class="localizations">
	<?php foreach ($this->captions as $caption):?>
	<tr>
		<td><?php echo $caption->name;?></td>
		
		<td><?php echo $caption->translate($caption->name, $this->caption_lang);?></td>
		
		<td style="width: 50px;padding: 5px;border-right:0px;">
			<span class="admin">
			<a href="<?php echo $this->url(array('id' => $caption->caption_id, 'loc_lang' => $this->caption_lang), 'edit_localization');?>">
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-pencil no-block" 
					alt="<?php echo $this->translate('edit');?>" 
					title="<?php echo $this->translate('edit');?>" />
			</a>
			<a href="<?php echo $this->url(array('id' => $caption->caption_id, 'loc_lang' => $this->caption_lang), 'delete_localization');?>"
				class="delete"> 
				<img src="/img/simple/empty.png" class="ui-icon ui-icon-trash no-block" 
					del="<?php echo $this->translate('delete');?>" 
					alt="<?php echo $this->translate('delete');?>" 
					title="<?php echo $this->translate('delete');?>" />
			</a>
			
			</span>
		</td>
	</tr>
	<?php endforeach;?>
	</table>
</div>