<div id="main">
	<h1>
	<?php echo $this->translate('localizations_header'); ?>
		<a href="<?php echo $this->url(array(), 'new_caption');?>"> <img
			src="/img/simple/empty.png"
			class="ui-icon ui-icon-plusthick no-block"
			alt="<?php echo $this->translate('new_caption');?>"
			title="<?php echo $this->translate('new_caption');?>" />
		</a>
	</h1>
	<div class="column-left">

	<?php $divide = count($this->captions)/2;?>

	<?php foreach ($this->captions as $index => $caption):?>
		<div class="caption">
			<h3>
				<span><?php echo $caption->name;?></span>
				<a
					href="<?php echo $this->url(array('id' => $caption->caption_id), 'edit_caption');?>">
					<img src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
					class="ui-icon ui-icon-pencil no-block"
					alt="<?php echo $this->translate('edit');?>"
					title="<?php echo $this->translate('edit');?>">
				</a> <a
					href="<?php echo $this->url(array('id' => $caption->caption_id), 'delete_caption');?>"
					class="delete"> <img
					src="<?php echo $this->baseUrl('img/simple/empty.png');?>"
					class="ui-icon ui-icon-trash no-block"
					alt="<?php echo $this->translate('delete');?>"
					title="<?php echo $this->translate('delete');?>">
				</a>
			</h3>
			
			
			<?php foreach($this->translations as $lang => $strings):?>
			<p>
				<strong><?php echo $lang;?></strong>:
				<?php 
					if (isset($strings[$caption->name]) && $strings[$caption->name] != null) 
						echo '<span>' . $strings[$caption->name] . '</span>';
					else
						echo '<span class="translation_missing" style="color:red">empty</span>';
				?>
				<a href="<?php echo $this->url(array('id' => $caption->caption_id, 'loc_lang' => $lang), 'edit_localization');?>"
					class="edit_translation" data-lang="<?php echo $lang;?>" data-caption-id="<?php echo $caption->caption_id;?>">
					<img src="/img/simple/empty.png" class="ui-icon ui-icon-pencil no-block" 
						alt="<?php echo $this->translate('edit');?>" 
						title="<?php echo $this->translate('edit');?>" />
				</a>
				<a href="<?php echo $this->url(array('id' => $caption->caption_id, 'loc_lang' => $lang), 'delete_localization');?>"
					class="delete"> 
					<img src="/img/simple/empty.png" class="ui-icon ui-icon-trash no-block" 
						del="<?php echo $this->translate('delete');?>" 
						alt="<?php echo $this->translate('delete');?>" 
						title="<?php echo $this->translate('delete');?>" />
				</a>
			</p>
			<?php endforeach;?>
		</div>
		
		
		
	<?php if (($index + 1) == (int)$divide):?>
	</div>
	<div class="column-right">

	<?php endif;?>

	<?php endforeach;?>
	</div>
</div>


<?php echo $this->partial('partials/delete_dialog.phtml',
array('title' => 'translation', 'delete_confirm' => $this->translate('translation_delete_confirm')));
?>
<img id="loader" src="<?php echo $this->baseUrl('/img/simple/ajax-loader.gif');?>" alt="performing request"/>