<div id="main">
	<h1><?php echo $this->translate('contact_header'); ?></h1>
	<p class="spacer">&nbsp;</p>
	
	<?php if (isset($this->error)):?>
	<h3><?php echo $this->translate('mail_error_header');?></h3>
	<p class="mailError"><?php echo $this->translate($this->error); ?></p>
	<?php else:?>
	<h3><?php echo $this->translate('mail_success_header');?></h3>
	<p class="mailSuccess"><?php echo $this->translate('mail_success'); ?></p>
	<?php endif;?>
</div>