<div id="main" class="content error">
  <h1><?php echo $this->translate('error_occured');?></h1>
  <h3><?php echo $this->translate($this->message);?></h3>

  <?php if (isset($this->exception)): ?>

  <h3><?php echo $this->translate('exception_information')?>:</h3>
  <p>
      <b><?php echo $this->translate('message')?>:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3><?php echo $this->translate('stack_trace')?>:</h3>
  	<?php foreach ($this->exceptionTrace as $string):?>
	<p class="error">
		<?php echo $string;?>
	</p>
  	<?php endforeach;?>
  
  

  <h3><?php echo $this->translate('request_parameters')?>:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ?>
</div>