<?php echo $this->partial('partials/delete_dialog.phtml',
			array('title' => 'file', 'delete_confirm' => $this->translate('news_image_delete_confirm')));
?>
<div id="main">
	<h1>
	<?php echo $this->translate('edit_news');?></h1>
	<div class="column-left">
		<?php echo $this->form;?>
	</div>

	<div class="column-right">
		<p class="label"><?php echo $this->translate('news_files');?></p>
		
		<?php foreach($this->news->files as $i => $file):?>
		<div id="file_<?php echo $file->news_file_id?>" style="width: 220px;float: left;margin: 5px 5px;">
		<p class="admin editNews">
			<a href="<?php echo $this->url(array('id'=> $file->news_file_id), 'news_image_delete');?>"
				class="remove-image" alt="file_<?php echo $i;?>">
				<img src="<?php echo $this->baseUrl('img/simple/empty.png');?>" class="ui-icon ui-icon-trash no-block"
					alt="<?php echo $this->translate('delete');?>"
					title="<?php echo $this->translate('delete');?>">
			</a>
		</p>
		<a 	class="form_file"
			href="<?php echo $this->baseUrl('/assets/images/'.$file->path);?>"
			rel="cache" >
			<img src="<?php echo $this->baseUrl('assets/images/'.$file->getImage('thumb'))?>" alt="" />
		</a>
		<?php if (++$i % 2 == 0):?><p class="clearfix"></p><?php endif;?>
		</div>
		<?php endforeach;?>
		
		<iframe id="newsfiles"
			src="<?php echo $this->url(array(), 'news_image');?>" width="480px"
			height="500px" scrolling="no" frameborder="0" seamless="seamless"></iframe>
	</div>
	<p class="clearfix"></p>

</div>



