<div id="main">
	<?php if ($this->user->role == 'admin'):?>
	<div class="news">
		<a href="<?php echo $this->url(array(),'new_news')?>">
			<img src="<?php echo $this->baseUrl('img/simple/new_news.png');?>" alt="zdjecie" width="220" />
		</a>
	</div>
	<?php endif;?>

	<?php foreach($this->news_list as $id => $news):?>
  	<div class="news"> 
  		<?php if ($this->user->role == 'admin') {$id = $id + 2;} else {$id = $id + 1;}?>
  		<!-- NEWS PHOTO -->
	  	<?php if ($news->hasPhoto()):?>
		  	<?php if ($news->link == ''):?>
	  		<a href="<?php echo $this->url(array('id' => $news->news_id),'show_news')?>">
		  		<img src="<?php echo $this->baseUrl('assets/images/'.$news->getImage('thumb'));?>" alt="zdjecie" width="220" />
		  	</a>
		  	<?php else:?>
		  	<a href="<?php echo $news->link?>">
		  		<img src="<?php echo $this->baseUrl('assets/images/'.$news->getImage('thumb'));?>" alt="zdjecie" width="220" />
		  	</a>
		    <?php endif;?>
	    <?php endif;?>
	    
	    <h2>
	    	<?php if ($news->link == ''):?>
	    	<a href="<?php echo $this->url(array('id' => $news->news_id),'show_news')?>"><?php echo $news->getDetail('news_title', $this->lang);?></a>
	    	<?php else:?>
	    	<a href="<?php echo $news->link ?>"><?php echo $news->getDetail('news_title', $this->lang);?></a>
	    	<?php endif;?>
	    </h2>
	    
	    <?php if ($news->link == ''):?>
	    <p class="data"><?php echo date('d.m.Y H:i', $news->added);?></p> 
	    <?php endif; ?>
	    
	    <p><?php echo $news->getDetail('news_lead', $this->lang);?></p>
	    
	    <?php if ($news->link == '' || $this->user->role == 'admin'):?>
	    <p>
	    	<a href="<?php echo $this->url(array('id' => $news->news_id),'show_news')?>" class="wiecej">
	    		<img src="<?php echo $this->baseUrl('img/simple/bullet.png');?>" />
	    	</a>
	    </p>
	    <?php endif;?>
	</div>
 	<?php if (($id) % 4 == 0): ?>
 	<!-- every 4 news -->
	<p class="clearfix"></p>
	<?php endif;?>
  	<?php endforeach;?>
	<p class="clearfix"></p>
	<!-- PAGINATION -->
	<div class="paginator">
		<?php for($i = ($this->start_pagination); $i <= ($this->end_pagination); $i++):?>
		<a class="strona <?php if ($i == $this->current_page):?>strona-selected<?php endif;?>" 
			href="#">
			<?php echo $i;?>
		</a>
		<?php endfor;?>	
		
		<a class="strona" href="#"><img src="<?php echo $this->baseUrl;?>img/simple/bullet.png" alt="next page" /></a> 
	</div>
</div>
