<div id="main">
	<div class="column-left">
		<h1><?php echo $this->news->getDetail('news_title', $this->lang);?></h1>
		<p class="data-artykulu"><?php echo date('d.m.Y H:i', $this->news->added);?></p>
		<p class="lead"><?php echo $this->news->getDetail('news_lead', $this->lang);?></p>
		
		<?php if (!preg_match('/^<p/',$this->news->getDetail('news_text', $this->lang))):?>
			<p><?php echo $this->news->getDetail('news_text', $this->lang);?></p>
		<?php else:?>
			<?php echo $this->news->getDetail('news_text', $this->lang);?>
		<?php endif;?>
		
	</div>
	
	<div class="column-right">
		<img src="<?php echo $this->baseUrl('assets/images/'.$this->news->getImage());?>" alt="zdjecie" width="100%"/>
	</div>
</div>
