<div id="main">

	<div class="column-left">

	<?php if ($this->user->_role == 'admin') echo $this->partial('news/_admin.phtml', array('news' => $this->news, 'lang' => $this->lang));?>
		<h1>
		<?php echo $this->news->getDetail('news_title', $this->lang);?></h1>
		<p class="data-artykulu">
		<?php echo date('d.m.Y', $this->news->added);?></p>
		<p class="lead">
		<?php echo $this->news->getDetail('news_lead', $this->lang);?></p>
		
		
		
		<?php if (!preg_match('/^<p/',$this->news->getDetail('news_text', $this->lang))):?>
			<p><?php echo $this->news->getDetail('news_text', $this->lang);?></p>
		<?php else:?>
			<?php echo $this->news->getDetail('news_text', $this->lang);?>
		<?php endif;?>
		
	</div>

	<div class="column-right">

	<?php foreach($this->news->files as $image):?>
		<img
			src="<?php echo $this->baseUrl('assets/images/'.$image->getImage('small'))?>"
			alt="zdjecie" width="100%" />
		
		
		<?php endforeach;?>
	</div>
</div>



<?php echo $this->partial('partials/delete_dialog.phtml',
array('title' => 'news', 'delete_confirm' => $this->translate('news_delete_confirm')));
?>
