<?php echo $this->doctype('HTML5') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?php echo $this->headTitle();?>
	<?php echo $this->headLink()->appendStylesheet($this->baseUrl.'css/'.$this->template.'.css')
								->appendStylesheet($this->baseUrl.'js/fancybox/jquery.fancybox-1.3.1.css') 
								->appendStylesheet($this->baseUrl.'css/jquery-ui-1.8.16.custom.css'); ?>
								
	<?php echo $this->headScript()->appendFile($this->baseUrl.'js/simple/ajax.js')
								  ->appendFile($this->baseUrl.'js/simple/script.js?time=1'); ?>
	
</head>
<body class="iframe">
<?php $files = $this->fileForm->getElement('news_files')->getValue();?>
	<div id="app_images">
	<?php foreach(array_map('trim',explode(',', $files)) as $i => $file):?>
		<?php if ($file != ''):?>
		<div>
			<p class="admin">
				<a href="<?php echo $file;?>" class="remove-image" >
					<img src="<?php echo $this->baseUrl('img/simple/empty.png');?>" class="ui-icon ui-icon-trash no-block" 
						alt="<?php echo $this->translate('delete');?>" 
						title="<?php echo $this->translate('delete');?>">
				</a>
			</p>
			<a 	class="form_file"
				href="<?php echo $this->baseUrl($file);?>"
				rel="cache" >
				<img src="<?php echo $this->baseUrl($file);?>" alt="" />
			</a>
		</div>
		<?php if (++$i % 4 == 0):?><p class="clearfix"></p><?php endif;?>
		<?php endif;?>
	<?php endforeach;?>
	</div>
	<?php
		echo $this->fileForm;
	?>
</body>
</html>