<p class="admin">
	<a href="<?php $this->baseUrl?>/regulations/edit">
		<img class="ui-icon ui-icon-pencil no-block" 
			alt="<?php echo $this->translate('edit');?>" 
			title="<?php echo $this->translate('edit');?>">
	</a>
	<a href="<?php $this->baseUrl?>/regulations/delete"
		class="delete">
		<img class="ui-icon ui-icon-trash no-block" 
			alt="<?php echo $this->translate('delete');?>" 
			title="<?php echo $this->translate('delete');?>">
	</a>
</p>