<?php echo $this->partial('partials/lang_menu.phtml', 
			array('link' => 'regulations/edit', 'lang' => $this->lang));
?>
<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'editions', 'delete_confirm' => $this->translate('regulation_delete_confirm')));
?>
<div class="content">
	<?php echo $this->partial('regulations/_admin.phtml');?>
	<h1><?php echo $this->translate('regulation_header');?></h1>
	<p class="spacer">&nbsp;</p>
	
	<?php if ($this->form->csrf->hasErrors()):?>
	<div id="error-csrf" class="error-div">
		<p class="error"><?php echo $this->translate('csrf_error')?></p>
	</div>
	<?php endif;?>
	
	<?php echo $this->regulations;?>
	
</div>

<?php echo $this->partial('partials/submenu.phtml',	array('regulations' => TRUE));
?>

<p class="spacer_small">&nbsp;</p> 
<p class="previous">
	<a href="<?php echo $this->baseUrl;?>">
		&lt; <?php echo $this->translate('previous_page');?>
	</a>
</p>
