<?php echo $this->partial('partials/lang_menu.phtml', 
			array('link' => 'regulations/edit', 'lang' => $this->lang));
?>
<div class="content">
	<?php echo $this->partial('regulations/_admin.phtml', array('baseUrl' => $this->baseUrl));?>
	<h1><?php echo $this->translate('regulation_header');?></h1>
	<p class="spacer">&nbsp;</p>
	
	<?php echo $this->regulations;?>
	
</div>

<?php echo $this->partial('partials/submenu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'regulations' => TRUE));
?>

<p class="spacer_small">&nbsp;</p> 
<p class="previous">
	<a href="<?php echo $this->baseUrl;?>">
		&lt; <?php echo $this->translate('previous_page');?>
	</a>
</p>
