<br />
<?php echo $this->partial('partials/lang_menu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'link' => 'regulations',
						'lang' => $this->lang));
?>
<div class="content">
	<h1><?php echo $this->translate('regulation_header');?></h1>
	<p class="spacer">&nbsp;</p>
	
	<?php foreach($this->regulations as $regulation):?>
	<p class="rule">
		<span style="font-weight: bold">&sect; <?php echo $regulation->_paragraph_no;?></span><br />
		<?php echo  $regulation->_paragraph_text;?>
	</p> 
	<?php endforeach; ?>
</div>

<?php echo $this->partial('partials/submenu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'regulations' => TRUE));
?>

<p class="spacer_small">&nbsp;</p> 
<p class="previous"><a href="<?php echo $this->baseUrl;?>">&lt; <?php echo $this->translate('previous_page');?></a></p>
