<?php echo $this->partial('partials/delete_dialog.phtml',
array('title' => 'paragraph', 'delete_confirm' => $this->translate('paragraph_delete_confirm')));
?>

<div id="main">
	<h1>

	<?php echo $this->translate('regulation_header');?></h1>
	<p class="spacer">&nbsp;</p>

	<div style="clear: both; overflow: hidden;" id="regulation">
	<?php foreach($this->columns as $side => $regulations):?>
		<div id="<?php echo $side;?>"
			class="connected column-<?php echo $side;?>">

			<?php foreach($regulations as $i => $regulation):?>
			<div id="item_<?php echo $regulation->paragraph_id;?>"
				class="sort_item">

				<?php echo $this->partial('regulations/_admin.phtml',
					array('lang' => $this->lang, 'regulation' => $regulation));?>

				<p class="rule color">
					<span class="regulation_number" style="font-weight: bold">&sect; <?php echo ++$i;?>
					</span> <br />
					<?php echo  nl2br($regulation->paragraph_text);?>
				</p>
			</div>
			<?php endforeach; ?>
		</div>
		<?php endforeach; ?>
	</div>

	<?php if (count($this->columns['left']) == 0):?>
	<p class="empty">
		<?php echo $this->translate('no_regulation_defined');?>
		<br /><br /><br /><br />
	</p>
	<?php endif;?>
	
	<p id="new_paragraph">
		<span class="new_rule">
			<a href="<?php echo $this->url(array(), 'new_regulation');?>"><?php echo  $this->translate('add_new_paragraph');?></a>
		</span> 
	</p>	
</div>
