<?php echo $this->partial('partials/lang_menu.phtml', 
			array('link' => 'schools', 'lang' => $this->lang));
?>
<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'editions', 'delete_confirm' => $this->translate('school_delete_confirm')));
?>

<div class="content">
	<h1>
		<?php echo $this->translate('schools');?>
		<a href="<?php echo $this->baseUrl('/schools/new');?>">
			<img class="ui-icon ui-icon-plusthick no-block"
				alt="<?php echo $this->translate('add_new_school');?>" 
				title="<?php echo $this->translate('add_new_school');?>" />
		</a>
	</h1>
	
	<br />
	<?php foreach ($this->schools as $id => $school):?>
	<p>
		<?php echo $school;?>
	
		<span class="admin">
		<a href="<?php echo $this->url(array('id' => $id), 'edit_school');?>">
			<img class="ui-icon ui-icon-pencil no-block" 
				alt="<?php echo $this->translate('edit');?>" 
				title="<?php echo $this->translate('edit');?>" />
		</a>
		<a href="<?php echo $this->url(array('id' => $id), 'delete_school');?>"
			class="delete"> 
			<img class="ui-icon ui-icon-trash no-block" 
				del="<?php echo $this->translate('delete');?>" 
				alt="<?php echo $this->translate('delete');?>" 
				title="<?php echo $this->translate('delete');?>" />
		</a>
		</span>
	</p>
	
	<?php endforeach;?>

</div>

<p class="spacer_small">&nbsp;</p> 
<p class="previous">
	<a href="<?php echo $this->baseUrl('/admin');?>">
	&lt; <?php echo $this->translate('previous_page');?>
	</a>
</p>
