<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'editions', 'delete_confirm' => $this->translate('school_delete_confirm')));
?>

<div id="main">
	<h1>
		<?php echo $this->translate('schools');?>
		<a href="<?php echo $this->baseUrl('/schools/new');?>">
			<img src="/img/simple/empty.png" class="ui-icon ui-icon-plusthick no-block"
				alt="<?php echo $this->translate('add_new_school');?>" 
				title="<?php echo $this->translate('add_new_school');?>" />
		</a>
	</h1>
	
	<br />
	<?php foreach ($this->schools as $id => $school):?>
	<p>
		<?php echo $school;?>
	
		<span class="admin">
		<a href="<?php echo $this->url(array('id' => $id), 'edit_school');?>">
			<img src="/img/simple/empty.png" class="ui-icon ui-icon-pencil no-block" 
				alt="<?php echo $this->translate('edit');?>" 
				title="<?php echo $this->translate('edit');?>" />
		</a>
		<a href="<?php echo $this->url(array('id' => $id), 'delete_school');?>"
			class="delete"> 
			<img src="/img/simple/empty.png" class="ui-icon ui-icon-trash no-block" 
				del="<?php echo $this->translate('delete');?>" 
				alt="<?php echo $this->translate('delete');?>" 
				title="<?php echo $this->translate('delete');?>" />
		</a>
		</span>
	</p>
	
	<?php endforeach;?>

</div>