<div id="main">
  <h1>

  <?php echo $this->translate('users_header');?>

  <?php if ($this->user->_role == 'admin'):?>
    <a href="<?php echo $this->baseUrl('/users/new');?>"> <img
      src="/img/simple/empty.png"
      class="ui-icon ui-icon-plusthick no-block"
      alt="<?php echo $this->translate('add_new_user');?>"
      title="<?php echo $this->translate('add_new_user');?>" />
    </a>
    
    
    <?php endif;?>
  </h1>
  <p class="clear">&nbsp;</p>
  
  
  <?php foreach ($this->users as $role => $groupedUsers):?>
    <h3><?php echo $this->translate($role.'s');?></h3>
    <?php foreach($groupedUsers as $user):?>
    <div class="user" id="element-<?php echo $user->user_id;?>">
      <?php if ($this->user->_role == 'admin')
      {
        echo $this->partial(
              'users/_admin.phtml', 
              array('user' => $user));  
      }?>
      <h4>
        <a href="<?php echo $this->url(array('id' => $user->user_id), 'user');?>">
          <?php echo $user->getUserFullName();?>
        </a>
      </h4>
      <p>
        <span><?php echo $this->translate('nick');?></span>: 
        <?php echo $user->nick;?>
      </p>
      <p>
        <span><?php echo $this->translate('email');?></span>: 
        <?php echo $user->email;?>
      </p>
      
    </div>
    <?php endforeach;?>    
  <?php endforeach;?>
</div>
<?php echo $this->partial('partials/delete_dialog.phtml',
array('title' => 'translation', 'delete_confirm' => $this->translate('user_delete_confirm')));
?>