<?php echo $this->partial('partials/lang_menu.phtml', 
			array('link' => 'users', 'lang' => $this->lang));
?>
<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'editions', 'delete_confirm' => $this->translate('user_delete_confirm')));
?>

<div class="content">
	<h1><?php echo $this->translate('users_header');?></h1>
	<p class="clear">&nbsp;</p>
	<?php foreach ($this->users as $role => $groupedUsers):?>
		<h3><?php echo $this->translate($role.'s');?></h3>
		<?php foreach($groupedUsers as $user):?>
		<div class="user">
			<?php echo $this->partial(
							'users/_admin.phtml', 
							array('user' => $user));	?>
			<h4>
				<a href="<?php echo $this->url(array('id' => $user->_user_id), 'user');?>">
					<?php echo $user->getUserFullName();?>
				</a>
			</h4>
			<p>
				<span><?php echo $this->translate('nick');?></span>: 
				<?php echo $user->_nick;?>
			</p>
			<p>
				<span><?php echo $this->translate('email');?></span>: 
				<?php echo $user->_email;?>
			</p>
			
		</div>
		<?php endforeach;?>		
	<?php endforeach;?>
</div>

<p class="spacer_small">&nbsp;</p> 
<p class="previous"><a href="<?php echo $this->baseUrl;?>">&lt; <?php echo $this->translate('previous_page');?></a></p>