<br />
<?php echo $this->partial('partials/lang_menu.phtml', 
			array(	'baseUrl' => $this->baseUrl,
						'link' => 'users',
						'lang' => $this->lang));
?>

<div class="content">
	<h1><?php echo $this->translate('new_user');?></h1>
	<?php echo $this->form;?>
</div>


<p class="spacer_small">&nbsp;</p> 
<p class="previous"><a href="<?php echo $this->baseUrl('/users');?>">&lt; <?php echo $this->translate('previous_page');?></a></p>