<?php echo $this->partial('partials/lang_menu.phtml', 
			array('link' => 'account/'.$this->account->user_id, 'lang' => $this->lang));
?>
<?php echo $this->partial('partials/delete_dialog.phtml', 
			array('title' => 'users', 'delete_confirm' => $this->translate('user_delete_confirm')));
?>
<div class="content">
	<h1><?php echo $this->account->getUserFullName();?></h1>
	<p class="clear">&nbsp;</p>
	<div class="account">
		<?php echo $this->partial(
							'users/_admin.phtml', 
							array('user' => $this->account));	?>
		<p>
			<span><?php echo $this->translate('nick');?></span>: 
			<?php echo $this->account->nick;?>
		</p>
		
		<p>
			<span><?php echo $this->translate('email');?></span>: 
			<?php echo $this->account->email;?>
		</p>
		
		<?php if ($this->account->phone != null):?>
		<p>
			<span><?php echo $this->translate('phone');?></span>: 
			<?php echo $this->account->phone;?>
		</p>
		<?php endif;?>
		
		<?php if ($this->account->address != null):?>
		<p>
			<span><?php echo $this->translate('address');?></span>: 
			<?php echo $this->account->address;?>
		</p>
		<?php endif; ?>
		
		<?php if ($this->account->applications != null):?>
		<p>
			<span><?php echo $this->translate('application');?></span>:
			<a href="<?php echo $this->url(array('id' => $this->account->applications[0]->application_id), 'application');?>"> 
				<?php echo $this->account->applications[0]->work_subject;?>
			</a>
		</p>
		<?php endif;?>
	</div>
</div>

<p class="spacer_small">&nbsp;</p> 
<p class="previous"><a href="<?php echo $this->baseUrl('/users');?>">&lt; <?php echo $this->translate('previous_page');?></a></p>