<div id="main">
	<?php foreach($this->news_list as $id => $news):?>
  	<div class="news"> 
  		<!-- NEWS PHOTO -->
	  	<a href="<?php echo $this->url(array('id' => $news->news_id),'show_news')?>">
	  		<img src="/assets/images/<?php echo $news->getImage();?>" alt="zdjecie" width="100%" />
	  	</a>
	    
	    <h2>
	    	<a href="<?php echo $this->url(array('id' => $news->news_id),'show_news')?>"><?php echo $news->getDetail('news_title', $this->lang);?></a>
	    </h2>
	    
	    <p class="data"><?php echo date('d.m.Y H:i', $news->added);?></p> 
	    
	    <p><?php echo $news->getDetail('news_text', $this->lang);?></p>
	    
	    <p>
	    	<a href="<?php echo $this->url(array('id' => $news->news_id),'show_news')?>" class="wiecej">
	    		<img src="/img/simple/bullet.png" />
	    	</a>
	    </p>
	</div>
	 	<?php if ($id % 4 == 0 or ($id+1) == count($this->news_list)): ?>
	 	<!-- every 4 news -->
		<div class="clear" />
		<?php endif;?>
  	<?php endforeach;?>

	<!-- PAGINATION -->
	<div class="paginator">
		<?php for($i = ($this->start_pagination); $i <= ($this->end_pagination); $i++):?>
		<a class="strona <?php if ($i == $this->current_page):?>strona-selected<?php endif;?>" 
			href="#">
			<?php echo $i;?>
		</a>
		<?php endfor;?>	
		
		<a class="strona"href="#"><img src="/img/simple/bullet.png" /></a> 
	</div>
</div>