<?php

class Application_Model_DbTable_DiplomaFiles extends Zefir_Application_Model_DbTable
{

	/**
	 * Name of the table without prefix
	 * @var string
	 */
	protected $_raw_name = 'diploma_files';

	/**
	 * Name of the table generated by the constructor
	 * @var string
	 */
	protected $_name = '';

	/**
	 * Primary key of the table
	 * @var string
	 */
	protected $_primary = 'file_id';


	/**
	 * An array of child tables information
	 * @var array
	 */
	protected $_belongsTo = array(
		'diploma' => array(
    		'model' => 'Application_Model_Results',
			'column' => 'diploma_id',
			'refColumn' => 'diploma_id'
	)
	);

	/**
	 * constructor
	 * @access public
	 * @param array $config
	 * @return void
	 */
	public function __construct($config = array())
	{
		parent::__construct(array());
	}

	/**
	 * Save or update file data in the database
	 *
	 * @param Application_Model_Files $file
	 * @throws Zend_Exception
	 * @return Application_Model_Files $file
	 */
	public function save(Application_Model_DiplomaFiles $file)
	{
		if ($file->file_id != null)
		$oldData = new Application_Model_DiplomaFiles($file->file_id);
		else
		$oldData = null;

		parent::save($file);
		 
		if (strstr($file->path, 'cache'))
		{
			//save file, otherwise save data only
			$options = Zend_Registry::get('options');
			$this->_copyFile($file, 'path', $options['upload']['diplomas'].$file->getFileFolder(), $file->getFileName(), $oldData);
		}
	}
}

