<?php

class Application_Model_DbTable_Fields extends Zefir_Application_Model_DbTable
{

	/**
	 * Name of the table without prefix
	 * @var string
	 */
    protected $_raw_name = 'fields';
    
     /**
     * Name of the table generated by the constructor
     * @var string
     */
    protected $_name = '';
    
    /**
	 * Primary key of the table
	 * @var string
	 */
    protected $_primary = 'field_id';


   /**
	 * An array of parent table information
	 * @var array
	 */
	protected $_hasMany = array(
		'result_fields' => array(
			'model' => 'Application_Model_ResultFields',
			'refColumn' => 'field_id',
		),
	);
	
	/**
	 * constructor
	 * @access public
	 * @param array $config
	 * @return void
	 */
    public function __construct($config = array())
    {
      parent::__construct(array());
    }
    
	/**
     * Save or update application data in the database 
     * 
     * @param Application_Model_ResultFields $result
     * @throws Zend_Exception
     * @return Application_Model_ResultFields $result
     */
	public function save(Application_Model_Fields $field)
    {
    		parent::save($field);
    }
    
    public function delete(Application_Model_Fields $field)
    {
		//remove field
    	parent::delete($result);
    }
    
    public function getField($name)
    {
    	$select = $this->select()->where('field_name = ?', $name);
    	
    	$row = $this->fetchRow($select);
    	if (count($row) == 0)
    	{//create new field with a given name
    		$row = $this->createRow();
    		$row->field_name = $name;
    		$row->save();
    	}
    	
    	return $row;
    }
}

