<?php

class Application_Model_DbTable_Files extends Zefir_Application_Model_DbTable
{

	/**
	 * Name of the table without prefix
	 * @var string
	 */
    protected $_raw_name = 'files';
    
     /**
     * Name of the table generated by the constructor
     * @var string
     */
    protected $_name = '';
    
    /**
	 * Primary key of the table
	 * @var string
	 */
    protected $_primary = 'file_id';


    /**
     * An array of child tables information
     * @var array
     */
    protected $_belongsTo = array(
		'application' => array(
    		'model' => 'Application_Model_Applications',
    		'column' => 'application_id',
			'refColumn' => 'application_id',
		)
	);
	
	/**
	 * constructor
	 * @access public
	 * @param array $config
	 * @return void
	 */
    public function __construct($config = array())
    {
      parent::__construct($config);
    }
    
    /**
     * Save or update file data in the database 
     * 
     * @param Application_Model_Files $file
     * @throws Zend_Exception
     * @return Application_Model_Files $file
     */
    public function save(Application_Model_Files $file)
    {
    	parent::save($file);
    }
}

