<?php

class Application_Model_DbTable_Files extends Zefir_Application_Model_DbTable
{

	/**
	 * Name of the table without prefix
	 * @var string
	 */
    protected $_raw_name = 'files';
    
     /**
     * Name of the table generated by the constructor
     * @var string
     */
    protected $_name = '';
    
    /**
	 * Primary key of the table
	 * @var string
	 */
    protected $_primary = 'file_id';


    /**
     * An array of child tables information
     * @var array
     */
    protected $_referenceMap = array(
		'Applications' => array(
    		'objProperty' => '_edition',
			'columns' => array('application_id'),
			'refTableClass' => 'Application_Model_DbTable_Applications',
			'refColumns' => array('application_id'),
			'onDelete' => self::CASCADE,
			'onUpdate' => self::RESTRICT
		)
	);
	
	/**
	 * An array of parent table information
	 * @var array
	 */
	protected $_dependentTables = array();
	
	/**
	 * constructor
	 * @access public
	 * @param array $config
	 * @return void
	 */
    public function __construct($config = array())
    {
      parent::__construct(array());
    }

}

