<?php

class Application_Model_DbTable_ResultFields extends Zefir_Application_Model_DbTable
{

	/**
	 * Name of the table without prefix
	 * @var string
	 */
    protected $_raw_name = 'result_fields';
    
     /**
     * Name of the table generated by the constructor
     * @var string
     */
    protected $_name = '';
    
    /**
	 * Primary key of the table
	 * @var string
	 */
    protected $_primary = 'result_field_id';


    /**
     * An array of child tables information
     * @var array
     */
     protected $_belongsTo = array(
    
    	'result' => array(
    		'model' => 'Application_Model_Results',
    		'column' => 'result_id',
			'refColumn' => 'result_id'
       	),

       	'lang' => array(
       		'model' => 'Application_Model_Languages',
			'column' => 'lang_id',
			'refColumn' => 'lang_id'
		),
		
		'field' => array(
       		'model' => 'Application_Model_Fields',
			'column' => 'field_id',
			'refColumn' => 'field_id'
		)
    );
	
	/**
	 * An array of parent table information
	 * @var array
	 */
	protected $_hasMany = array(
		'files' => array(
			'model' => 'Application_Model_ResultFiles',
			'refColumn' => 'result_id',
		),
		
		'fields' => array(
			'model' => 'Application_Model_ResultFields',
			'refColumn' => 'result_id',
		),
	);
	
	/**
	 * constructor
	 * @access public
	 * @param array $config
	 * @return void
	 */
    public function __construct($config = array())
    {
      parent::__construct(array());
    }
    
	/**
     * Save or update application data in the database 
     * 
     * @param Application_Model_ResultFields $result
     * @throws Zend_Exception
     * @return Application_Model_ResultFields $result
     */
	public function save(Application_Model_ResultFields $result)
    {
    		parent::save($application);
    }
    
    public function delete(Application_Model_ResultFields $result)
    {
		$options = Zend_Registry::get('options');
    	
    	//remove files
    	$this->_deleteApplicationFiles($result->_files);
    	
    	//remove miniature
    	$path = APPLICATION_PATH.'/../public'.$options['upload']['miniatures'].'/'.$result->_miniature;
    	unlink($path);
    	
    	//remove application
    	parent::delete($result);
    }
    
    protected function _deleteApplicationFiles($files)
    {
    	$options = Zend_Registry::get('options');
    	foreach($files as $file)
    	{
    		$dir = APPLICATION_PATH.'/../public'.$options['upload']['applications'].'/'.substr($file->_path, 0, strrpos($file->_path, '/'));
    		$path = APPLICATION_PATH.'/../public'.$options['upload']['applications'].'/'.$file->_path;
    		//unlink($path);
    		$file->delete();
    	}
    	
    	//rmdir($dir);
    }
}

