<?php

class Application_Model_DbTable_Files extends Zefir_Application_Model_DbTable
{

	/**
	 * Name of the table without prefix
	 * @var string
	 */
    protected $_raw_name = 'result_files';
    
     /**
     * Name of the table generated by the constructor
     * @var string
     */
    protected $_name = '';
    
    /**
	 * Primary key of the table
	 * @var string
	 */
    protected $_primary = 'file_id';


    /**
     * An array of child tables information
     * @var array
     */
    protected $_referenceMap = array(
		'Results' => array(
    		'objProperty' => '_result',
			'columns' => array('result_id'),
			'refTableClass' => 'Application_Model_DbTable_Results',
			'refColumns' => array('result_id'),
			'onDelete' => self::CASCADE,
			'onUpdate' => self::RESTRICT
		)
	);
	
	/**
	 * An array of parent table information
	 * @var array
	 */
	protected $_dependentTables = array();
	
	/**
	 * constructor
	 * @access public
	 * @param array $config
	 * @return void
	 */
    public function __construct($config = array())
    {
      parent::__construct(array());
    }
    
    /**
     * Save or update file data in the database 
     * 
     * @param Application_Model_Files $file
     * @throws Zend_Exception
     * @return Application_Model_Files $file
     */
    public function save(Application_Model_Files $file)
    {
    	parent::save($file);
    }
}

