<?php

class Application_Model_DbTable_Settings extends Zefir_Application_Model_DbTable
{
	/**
	 * Name of the table without prefix
	 * @var string
	 */
    protected $_raw_name = 'settings';
        
     /**
     * Name of the table generated by the constructor
     * @var string
     */
	protected $_name = '';
    
    /**
	 * Primary key of the table
	 * @var string
	 */
    protected $_primary = 'current_edition';

    /**
     * An array of child tables information
     * @var array
     */
    protected $_referenceMap = array(
		'Editions' => array(
    		'objProperty' => '_current_edition',
			'columns' => array('current_edition'),
			'refTableClass' => 'Application_Model_DbTable_Editions',
			'refColumns' => array('edition_id'),
			'onDelete' => self::CASCADE,
			'onUpdate' => self::RESTRICT
		),
		'TemplateSettings' => array(
    		'objProperty' => '_template_default',
			'columns' => array('template_default'),
			'refTableClass' => 'Application_Model_DbTable_TemplateSettings',
			'refColumns' => array('template_id'),
			'onDelete' => self::CASCADE,
			'onUpdate' => self::RESTRICT
		)
	);
	
	/**
	 * An array of parent table information
	 * @var array
	 */
	protected $_dependentTables = array();
	
	/**
	 * constructor
	 * @access public
	 * @param array $config
	 * @return void
	 */
    public function __construct($config = array())
    {
      parent::__construct(array());
    }
    
    public function getSettings(Application_Model_Settings $settings)
    {
    	$select = $this->select()->order('current_edition DESC')->limit('1');
    	$row = $this->fetchRow($select);
    	$settings->populateWithReference($row);
    	
    	return $settings;
    }
    
    
    public function save(Application_Model_Settings $settings)
    {
    	$row = $this->fetchAll()->current();
    	
    	$row->current_edition 		= $settings->_current_edition;
    	$row->template_default 		= $settings->_template_default;
    	$row->max_file_size 		= $settings->_max_file_size;
    	$row->date_format 			= $settings->_date_format;
    	$row->max_files 			= $settings->_max_files;
    	$row->work_start_date 		= $settings->_work_start_date;
    	$row->work_end_date 		= $settings->_work_end_date;
    	$row->application_deadline 	= $settings->_application_deadline;
    	$row->result_date	 		= $settings->_result_date;
    	
    	if (!$row->save())
    	{
    		throw new Zend_Exception('Couldn\'t save settings');
    	}

    	return $settings;
    }

}

